import { ArrowRight, MapPin } from 'lucide-react';
import { ArrowLink, LinkButton } from '@/components/baru-ui';
import { PublicLayout } from '@/components/public-shell';
import { content, menuItems, moments, photoUrls, settings } from '@/lib/baru-data';

export default function HomePage() {
  const featured = menuItems.filter((item) => item.featured).slice(0, 3);
  return <PublicLayout><main><section className="hero" style={{ '--hero-image': `url(${content.heroImageUrl})` } as React.CSSProperties}><div className="hero__inner"><p className="eyebrow">{settings.city}</p><h1>{content.heroTitle}</h1><p>{content.heroSubtitle}</p><div className="hero__actions"><LinkButton href="/reservar">Reservar mesa <ArrowRight size={16} /></LinkButton><LinkButton href="/cardapio" variant="secondary">Ver cardápio</LinkButton></div></div><p className="hero__note">Boa comida<br />aproxima pessoas.</p></section><section id="o-baru" className="moments-section"><div className="public-section"><div className="moment-grid"><div className="moment-intro"><p className="eyebrow">Três momentos, uma só essência</p><h2>O dia encontra o seu sabor.</h2><p className="muted">Do café da manhã ao último brinde, cada momento é um convite para viver o presente com mais sabor.</p></div>{moments.map((moment) => <a className="moment-card" href={`/cardapio?momento=${moment.id}`} key={moment.id}><img src={moment.imageUrl} alt="" /><span className="moment-card__arrow"><ArrowRight size={16} /></span><div className="moment-card__text"><h3>{moment.name}</h3><p>{moment.eyebrow}</p></div></a>)}</div></div></section><section id="experiencia" className="public-section"><div className="section-heading"><div><p className="eyebrow">Nossos destaques</p><h2>Sabores que contam histórias.</h2></div><ArrowLink href="/cardapio">Ver cardápio completo</ArrowLink></div><div className="feature-grid">{featured.map((item) => <article className="feature-card" key={item.id}><img src={item.imageUrl} alt={item.name} /><div className="feature-card__body"><h3>{item.name}</h3><p>{item.description}</p></div></article>)}</div></section><section id="chef" className="chef-band"><img src={content.chefImageUrl} alt={`Chef ${content.chefName} preparando um prato`} /><div className="chef-band__body"><p className="eyebrow">Nosso chef</p><h2>{content.chefName}</h2><p>{content.chefBio}</p><div className="quote">“{content.quote}”</div></div></section><section className="public-section"><div className="section-heading"><div><p className="eyebrow">Mais que uma refeição</p><h2>Uma experiência completa.</h2><p>Boa comida, bons encontros, um ambiente único. Cada detalhe no Baru foi pensado para tornar o seu momento especial.</p></div><div id="localizacao" className="summary-line"><MapPin size={18} /><span>{settings.address}</span></div></div><div className="gallery-grid">{content.gallery.map((image, index) => <img key={image} src={image} alt={index === 0 ? 'Ambiente do restaurante Baru' : 'Detalhe da experiência Baru'} />)}</div></section><section className="cta-band" style={{ '--cta-image': `url(${photoUrls.room})` } as React.CSSProperties}><div className="cta-band__inner"><div><p className="eyebrow">Sabor, conexão e bons momentos</p><h2>Faça sua reserva.</h2></div><LinkButton href="/reservar">Reservar mesa <ArrowRight size={16} /></LinkButton></div></section></main></PublicLayout>;
}
