'use client';

import { CalendarDays, Check, ChevronRight, CircleAlert, Clock3, Edit3, ExternalLink, Image as ImageIcon, MapPin, MessageCircle, MoreHorizontal, Plus, Save, Search, Settings2, Table2, UserPlus, Users, Utensils, X } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { AdminPage } from '@/components/admin-shell';
import { Button, LinkButton, StatCard, StatusBadge } from '@/components/baru-ui';
import { areas, categories, content, conversations, customers, menuItems, photoUrls, reservations as seedReservations, settings, tables, team } from '@/lib/baru-data';
import { buildWhatsappLink, createReservation, readReservations, updateReservation } from '@/lib/baru-repository';
import { formatDate, formatMoney, normalizeWhatsapp, RESERVATION_STATUS_LABELS, ROLE_LABELS, type ReservationStatus } from '@/shared/baru-domain';

export function ReservationManager() {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState<'ALL' | ReservationStatus>('ALL');
  const [items] = useState(() => readReservations());
  const filtered = items.filter((item) => (status === 'ALL' || item.status === status) && `${item.customerName} ${item.code} ${item.whatsapp}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminPage active="/admin/reservas" title="Reservas" subtitle="Gerencie as reservas do restaurante." actions={<LinkButton href="/admin/reservas/nova"><Plus size={17} /> Nova reserva</LinkButton>}><div className="admin-toolbar"><div className="filter-pills">{(['ALL', 'NEW', 'CONFIRMED', 'ARRIVED', 'COMPLETED', 'CANCELLED'] as const).map((value) => <button key={value} className={`filter-pill ${status === value ? 'active' : ''}`} onClick={() => setStatus(value)}>{value === 'ALL' ? 'Todas' : value === 'NEW' ? 'Pendentes' : RESERVATION_STATUS_LABELS[value]}</button>)}</div><label className="field-shell" style={{ minWidth: 260 }}><Search size={16} /><span className="visually-hidden">Buscar reserva</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar nome, telefone ou código…" /></label></div><section className="admin-panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Código</th><th>Cliente</th><th>Data e horário</th><th>Pessoas</th><th>Mesa</th><th>Status</th><th aria-label="Ações" /></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td className="table-primary">#{item.code.replace('BRU-', '')}</td><td><div className="table-primary">{item.customerName}</div><div className="table-secondary">{item.whatsapp}</div></td><td>{formatDate(item.date)}<div className="table-secondary">{item.time}</div></td><td>{item.partySize}</td><td>{item.tableId?.replace('mesa-', 'Mesa ') || '—'}</td><td><StatusBadge status={item.status} /></td><td><a className="icon-button" href={`/admin/reservas/${item.id}/editar`} aria-label={`Editar ${item.code}`}><Edit3 size={15} /></a></td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state"><CircleAlert size={20} /><h2>Nenhuma reserva encontrada</h2><p>Altere os filtros ou cadastre uma nova reserva.</p></div>}</div></section></AdminPage>;
}

function ReservationFields({ form, setForm, includeStatus = false }: { form: { name: string; whatsapp: string; date: string; time: string; partySize: string; tableId: string; note: string; status: ReservationStatus }; setForm: (next: (current: typeof form) => typeof form) => void; includeStatus?: boolean }) {
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="form-stack"><label className="form-label"><span>Cliente *</span><input value={form.name} onChange={(event) => set('name', event.target.value)} placeholder="Nome completo" required /></label><label className="form-label"><span>WhatsApp *</span><input value={form.whatsapp} onChange={(event) => set('whatsapp', event.target.value)} placeholder="(45) 9 9988-7766" required /></label><div className="form-row"><label className="form-label"><span>Data *</span><input type="date" value={form.date} onChange={(event) => set('date', event.target.value)} required /></label><label className="form-label"><span>Horário *</span><select value={form.time} onChange={(event) => set('time', event.target.value)} required><option value="">Selecione</option>{['12:00', '12:30', '13:00', '13:30', '19:00', '19:30', '20:00', '20:30', '21:00'].map((time) => <option key={time}>{time}</option>)}</select></label></div><div className="form-row"><label className="form-label"><span>Pessoas *</span><select value={form.partySize} onChange={(event) => set('partySize', event.target.value)}>{Array.from({ length: 20 }, (_, index) => <option key={index + 1}>{index + 1}</option>)}</select></label><label className="form-label"><span>Área / Mesa *</span><select value={form.tableId} onChange={(event) => set('tableId', event.target.value)}>{tables.filter((table) => table.capacity >= Number(form.partySize)).map((table) => <option key={table.id} value={table.id}>{table.name} · {table.capacity} lugares</option>)}</select></label></div><label className="form-label"><span>Observação</span><textarea value={form.note} onChange={(event) => set('note', event.target.value)} maxLength={500} /></label>{includeStatus && <label className="form-label"><span>Status inicial</span><select value={form.status} onChange={(event) => set('status', event.target.value as ReservationStatus)}>{(Object.keys(RESERVATION_STATUS_LABELS) as ReservationStatus[]).map((value) => <option key={value} value={value}>{RESERVATION_STATUS_LABELS[value]}</option>)}</select></label>}</div>;
}

export function NewReservationForm() {
  const [form, setForm] = useState({ name: '', whatsapp: '', date: '2026-09-24', time: '', partySize: '2', tableId: tables[0].id, note: '', status: 'CONFIRMED' as ReservationStatus });
  const [error, setError] = useState('');
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!form.name.trim() || !form.time || !form.whatsapp.trim()) { setError('Preencha cliente, WhatsApp e horário.'); return; } try { const reservation = createReservation({ customerId: `customer-${form.name.toLowerCase().replace(/\W+/g, '-')}`, customerName: form.name.trim(), whatsapp: normalizeWhatsapp(form.whatsapp), date: form.date, time: form.time, partySize: Number(form.partySize), tableId: form.tableId, note: form.note.trim(), status: form.status, source: 'ADMIN' }); window.location.href = `/admin/reservas/${reservation.id}/editar`; } catch { setError('Não foi possível criar a reserva.'); } };
  return <AdminPage active="/admin/reservas" title="Nova reserva" subtitle="Cadastre rapidamente uma nova reserva."><div className="admin-form-card"><form className="form-card" onSubmit={submit}><h2>Dados da reserva</h2><ReservationFields form={form} setForm={setForm} includeStatus />{error && <p className="field-error" role="alert">{error}</p>}<div className="form-actions"><LinkButton href="/admin/reservas" variant="ghost">Cancelar</LinkButton><Button type="submit"><Save size={16} /> Criar reserva <ChevronRight size={16} /></Button></div></form><aside className="side-summary"><h2>Resumo da reserva</h2><img src={photoUrls.table} alt="Mesa preparada no Baru" /><div className="summary-line"><CalendarDays size={16} /> {form.date ? formatDate(form.date) : 'Escolha a data'}</div><div className="summary-line"><Clock3 size={16} /> {form.time || 'Escolha o horário'}</div><div className="summary-line"><Users size={16} /> {form.partySize} pessoas</div><div className="summary-line"><Table2 size={16} /> {form.tableId.replace('mesa-', 'Mesa ')}</div></aside></div></AdminPage>;
}

export function EditReservationForm({ id }: { id: string }) {
  const original = readReservations().find((item) => item.id === id) || seedReservations[0];
  const [form, setForm] = useState({ name: original.customerName, whatsapp: original.whatsapp, date: original.date, time: original.time, partySize: String(original.partySize), tableId: original.tableId || tables[0].id, note: original.note, status: original.status });
  const [saved, setSaved] = useState(false);
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); updateReservation(id, { customerName: form.name, whatsapp: form.whatsapp, date: form.date, time: form.time, partySize: Number(form.partySize), tableId: form.tableId, note: form.note, status: form.status }); setSaved(true); };
  return <AdminPage active="/admin/reservas" title="Editar reserva" subtitle="Altere as informações da reserva abaixo."><div className="admin-form-card"><form className="form-card" onSubmit={save}><div className="code-panel" style={{ marginTop: 0 }}><div><small>Código da reserva</small><strong>{original.code}</strong></div><StatusBadge status={form.status} /></div><h2>Informações da reserva</h2><ReservationFields form={form} setForm={setForm} includeStatus /><div className="form-actions"><Button type="submit"><Save size={16} /> Salvar alterações</Button><Button type="button" variant="dark" onClick={() => setForm((current) => ({ ...current, status: 'CONFIRMED' }))}><Check size={16} /> Confirmar reserva</Button><LinkButton href={buildWhatsappLink(form.whatsapp, `Olá, ${form.name}! Falamos sobre a reserva ${original.code}.`)} variant="ghost"><MessageCircle size={16} /> WhatsApp</LinkButton></div>{saved && <p className="field-error" style={{ color: 'var(--success)' }} role="status">Alterações salvas na demonstração.</p>}</form><aside className="side-summary"><h2>Histórico da reserva</h2><div className="timeline">{original.history.map((entry) => <div className="timeline-item" key={entry.id}><strong>{entry.label}</strong>{formatDate(entry.createdAt.slice(0, 10))} · por {entry.by}</div>)}</div><div className="settings-card" style={{ marginTop: 28 }}><strong>Dados de operação</strong><p>Origem: {original.source}<br />Última atualização: {formatDate(original.updatedAt.slice(0, 10))}</p></div></aside></div></AdminPage>;
}

export function AgendaView() {
  return <AdminPage active="/admin/agenda" title="Agenda" subtitle="Organize hoje grandes experiências." actions={<LinkButton href="/admin/reservas/nova"><Plus size={17} /> Nova reserva</LinkButton>}><div className="admin-grid"><StatCard icon={<Users size={19} />} label="Ocupação do dia" value="68%" detail="↑ 12% vs. semana anterior" tone="olive" /><StatCard icon={<CalendarDays size={19} />} label="Total de reservas" value="28" detail="112 pessoas" /><StatCard icon={<Clock3 size={19} />} label="Horário mais movimentado" value="19–21h" detail="62 pessoas" tone="gold" /><StatCard icon={<CircleAlert size={19} />} label="Pendentes" value="3" detail="Ver pendências" /></div><section className="admin-panel"><header className="admin-panel__header"><h2>Segunda-feira, 21 de setembro de 2026</h2><div className="filter-pills"><button className="filter-pill active">Dia</button><button className="filter-pill">Semana</button></div></header><div className="admin-panel__body"><div className="table-wrap"><table className="data-table"><thead><tr><th>Horário</th>{areas.map((area) => <th key={area.id}>{area.name}</th>)}</tr></thead><tbody>{['12:30', '13:00', '13:30', '14:00', '19:00', '19:30', '20:00', '21:00'].map((time) => <tr key={time}><td className="table-primary">{time}</td>{areas.map((area, index) => { const reservation = seedReservations.find((item) => item.time === time && index === (item.partySize % 4)); return <td key={area.id}>{reservation ? <a className="settings-card" style={{ display: 'block', padding: 10, background: reservation.status === 'NEW' ? '#faedcf' : '#e5efdf' }} href={`/admin/reservas/${reservation.id}/editar`}><strong style={{ fontSize: 12 }}>{reservation.customerName}</strong><span className="table-secondary">{reservation.partySize} pessoas · {reservation.status === 'NEW' ? 'Aguardando' : 'Confirmada'}</span></a> : <span className="muted">—</span>}</td>})}</tr>)}</tbody></table></div></div></section></AdminPage>;
}

export function CustomersView() {
  const [query, setQuery] = useState('');
  const filtered = customers.filter((customer) => `${customer.name} ${customer.whatsapp} ${customer.notes}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminPage active="/admin/clientes" title="Clientes" subtitle="Acompanhe histórico de reservas, contatos, no-show e observações." actions={<Button><UserPlus size={17} /> Novo cliente</Button>}><div className="admin-toolbar"><label className="field-shell" style={{ flex: 1, maxWidth: 600 }}><Search size={16} /><span className="visually-hidden">Buscar clientes</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome, telefone ou observação…" /></label><div className="filter-pills"><button className="filter-pill active">Todos ({customers.length})</button><button className="filter-pill">Recorrentes</button><button className="filter-pill">Aniversariantes</button></div></div><section className="admin-panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Cliente</th><th>Última reserva</th><th>Total</th><th>No-show</th><th>Contato</th><th>Observações</th><th /></tr></thead><tbody>{filtered.map((customer) => <tr key={customer.id}><td><a className="table-primary" href={`/admin/clientes/${customer.id}`}>{customer.name}</a><div className="table-secondary">{customer.tags.join(' · ')}</div></td><td>{customer.lastVisit ? formatDate(customer.lastVisit) : '—'}</td><td>{customer.reservationIds.length}</td><td>{customer.noShows}</td><td><a className="panel-link" href={buildWhatsappLink(customer.whatsapp, `Olá, ${customer.name}!`)}><MessageCircle size={16} /></a></td><td className="table-secondary">{customer.notes}</td><td><MoreHorizontal size={17} /></td></tr>)}</tbody></table></div></section></AdminPage>;
}

export function CustomerDetailView({ id }: { id: string }) {
  const customer = customers.find((item) => item.id === id) || customers[0];
  const customerReservations = readReservations().filter((item) => item.customerId === customer.id || item.customerName === customer.name);
  return <AdminPage active="/admin/clientes" title={customer.name} subtitle={`Cliente desde 12 de março de 2024 · ${customer.reservationIds[0] ? `#${customer.reservationIds[0].replace('res-', '')}` : ''}`} actions={<><LinkButton href="/admin/reservas/nova"><Plus size={16} /> Nova reserva</LinkButton><LinkButton href={buildWhatsappLink(customer.whatsapp, `Olá, ${customer.name}!`)} variant="ghost"><MessageCircle size={16} /> WhatsApp</LinkButton></>}><div className="filter-pills" style={{ marginBottom: 18 }}>{customer.tags.map((tag) => <span className="filter-pill active" key={tag}>{tag}</span>)}{customer.preferences.map((tag) => <span className="filter-pill" key={tag}>{tag}</span>)}</div><div className="admin-grid"><StatCard icon={<CalendarDays size={19} />} label="Total de reservas" value={String(customer.reservationIds.length || 0)} detail="↑ 12% vs. ano anterior" /><StatCard icon={<Users size={19} />} label="Comparecimentos" value={String(Math.max(0, customer.reservationIds.length - customer.noShows))} detail="86% de presença" tone="olive" /><StatCard icon={<CircleAlert size={19} />} label="No-show" value={String(customer.noShows)} detail="Acompanhar" tone="gold" /><StatCard icon={<Utensils size={19} />} label="Ticket médio" value="R$ 286" detail="↑ 18% vs. outros clientes" /></div><div className="admin-two-col"><section className="admin-panel"><header className="admin-panel__header"><h2>Últimas reservas</h2><a className="panel-link" href="/admin/reservas">Ver todas <ArrowRightIcon /></a></header><div className="admin-panel__body"><div className="data-list">{customerReservations.length ? customerReservations.map((reservation) => <div className="data-row" key={reservation.id}><strong>{formatDate(reservation.date)}</strong><div><div className="data-row__name">{reservation.time}</div><div className="data-row__meta">{reservation.partySize} pessoas · {reservation.tableId || 'Mesa não definida'}</div></div><StatusBadge status={reservation.status} /><a href={`/admin/reservas/${reservation.id}/editar`}><ChevronRight size={16} /></a></div>) : <p className="muted">Nenhuma reserva encontrada no modo demo.</p>}</div></div></section><section className="admin-panel"><header className="admin-panel__header"><h2>Observações da equipe</h2><Edit3 size={16} /></header><div className="admin-panel__body"><p>{customer.notes}</p><hr style={{ border: 0, borderTop: '1px solid var(--line)', margin: '24px 0' }} /><h2 style={{ fontSize: 22 }}>Preferências</h2>{customer.preferences.map((preference) => <div className="summary-line" key={preference}><Check size={16} /> {preference}</div>)}</div></section></div></AdminPage>;
}

function ArrowRightIcon() { return <ChevronRight size={14} style={{ verticalAlign: 'middle' }} />; }

export function MenuManagerView() {
  const [selected, setSelected] = useState('principais');
  const items = menuItems.filter((item) => item.categoryId === selected);
  return <AdminPage active="/admin/cardapio" title="Gerenciar cardápio" subtitle="Crie, edite e organize os itens do seu cardápio." actions={<Button><Plus size={17} /> Novo item</Button>}><div className="card-grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', marginBottom: 22 }}>{categories.map((category) => <button className={`settings-card ${selected === category.id ? 'active' : ''}`} style={{ textAlign: 'left', borderColor: selected === category.id ? 'var(--terracotta)' : 'var(--line)' }} key={category.id} onClick={() => setSelected(category.id)}><img src={menuItems.find((item) => item.categoryId === category.id)?.imageUrl} alt="" style={{ width: '100%', height: 90, objectFit: 'cover', marginBottom: 11 }} /><strong style={{ fontFamily: 'Georgia, serif', fontSize: 19 }}>{category.name}</strong><p style={{ margin: '5px 0 0' }}>{menuItems.filter((item) => item.categoryId === category.id).length} itens</p></button>)}</div><section className="admin-panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Item</th><th>Categoria</th><th>Preço</th><th>Status</th><th>Destaque</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><img src={item.imageUrl} alt="" style={{ width: 54, height: 42, objectFit: 'cover' }} /><div><div className="table-primary">{item.name}</div><div className="table-secondary">{item.description}</div></div></div></td><td>{categories.find((category) => category.id === item.categoryId)?.name}</td><td>{formatMoney(item.priceCents)}</td><td><StatusBadge status={item.active ? 'CONFIRMED' : 'CANCELLED'} /></td><td>{item.featured ? '★' : '☆'}</td><td><button className="icon-button" aria-label={`Editar ${item.name}`}><Edit3 size={15} /></button></td></tr>)}</tbody></table></div></section></AdminPage>;
}

export function TablesView() {
  return <AdminPage active="/admin/mesas" title="Mesas e áreas" subtitle="Gerencie as áreas do restaurante e suas mesas." actions={<><Button variant="ghost"><Plus size={16} /> Nova área</Button><Button><Plus size={16} /> Nova mesa</Button></>}><div className="card-grid">{areas.map((area) => { const areaTables = tables.filter((table) => table.areaId === area.id || area.id === 'salao'); return <article className="settings-card" key={area.id}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10 }}><div><p className="eyebrow">Área ativa</p><h2>{area.name}</h2><p>{areaTables.length} mesas · {areaTables.reduce((sum, table) => sum + table.capacity, 0)} lugares</p></div><Edit3 size={17} /></div><div className="data-list">{areaTables.slice(0, 5).map((table) => <div className="data-row" key={`${area.id}-${table.id}`} style={{ gridTemplateColumns: '1fr auto' }}><div><strong>{table.name}</strong><div className="table-secondary">{table.capacity} lugares</div></div><StatusBadge status={table.state === 'AVAILABLE' ? 'CONFIRMED' : table.state === 'MAINTENANCE' ? 'CANCELLED' : 'NEW'} /></div>)}</div></article>; })}</div></AdminPage>;
}

export function InboxView() {
  const [selected, setSelected] = useState(conversations[0]);
  return <AdminPage active="/admin/atendimento" title="Atendimento / WhatsApp" subtitle="Gerencie conversas, confirmações e suporte aos seus clientes." actions={<Button><Plus size={17} /> Nova mensagem</Button>}><div className="admin-two-col" style={{ gridTemplateColumns: '1fr 1.35fr' }}><section className="admin-panel"><header className="admin-panel__header"><h2>Conversas</h2><span className="muted">{conversations.length} ativas</span></header><div className="admin-panel__body" style={{ padding: 0 }}>{conversations.map((conversation) => <button key={conversation.id} onClick={() => setSelected(conversation)} style={{ width: '100%', display: 'grid', gridTemplateColumns: '38px 1fr auto', gap: 10, alignItems: 'center', padding: 15, border: 0, borderBottom: '1px solid var(--line)', background: selected.id === conversation.id ? 'var(--cream)' : '#fff', textAlign: 'left', cursor: 'pointer' }}><span className="avatar">{conversation.customerName.slice(0, 2).toUpperCase()}</span><span><strong>{conversation.customerName}</strong><small className="table-secondary" style={{ display: 'block' }}>{conversation.preview}</small></span><StatusBadge status={conversation.status === 'DONE' ? 'COMPLETED' : conversation.status === 'NEW' ? 'NEW' : 'CONFIRMED'} /></button>)}</div></section><section className="admin-panel"><header className="admin-panel__header"><div><h2>{selected.customerName}</h2><span className="muted">WhatsApp · atendimento demo</span></div><a className="icon-button" href={buildWhatsappLink('5545999876543', '')} aria-label="Abrir WhatsApp"><ExternalLink size={16} /></a></header><div className="admin-panel__body"><div className="timeline" style={{ minHeight: 290 }}>{selected.messages.map((message) => <div className="settings-card" style={{ maxWidth: '82%', marginLeft: message.from === 'TEAM' ? 'auto' : 0, background: message.from === 'TEAM' ? '#e5efdf' : 'var(--cream)' }} key={message.id}>{message.text}<div className="table-secondary" style={{ marginTop: 8 }}>{message.at}</div></div>)}</div><div className="form-row" style={{ marginTop: 20 }}><input className="field-shell" placeholder="Digite uma mensagem…" /><Button><MessageCircle size={16} /> Enviar</Button></div><div className="quick-actions" style={{ gridTemplateColumns: 'repeat(3, 1fr)' }}><button className="quick-action"><Check size={18} /> Confirmar reserva</button><button className="quick-action"><CalendarDays size={18} /> Criar reserva</button><button className="quick-action"><Utensils size={18} /> Enviar cardápio</button></div></div></section></div></AdminPage>;
}

export function TeamView() {
  const [selected, setSelected] = useState(team[0]);
  return <AdminPage active="/admin/equipe" title="Equipe" subtitle="Gerencie os usuários do sistema, função e permissões." actions={<Button><UserPlus size={17} /> Convidar usuário</Button>}><section className="admin-panel"><div className="admin-toolbar" style={{ padding: '18px 22px', margin: 0, borderBottom: '1px solid var(--line)' }}><label className="field-shell" style={{ flex: 1, maxWidth: 560 }}><Search size={16} /><input placeholder="Buscar por nome, e-mail ou função…" /></label><select className="field-shell" style={{ minHeight: 46, border: '1px solid var(--line)' }}><option>Todos os status</option><option>Ativos</option><option>Suspensos</option></select></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Nome</th><th>Função</th><th>Permissões</th><th>Status</th><th>Último acesso</th><th /></tr></thead><tbody>{team.map((member) => <tr key={member.id} onClick={() => setSelected(member)} style={{ cursor: 'pointer', background: selected.id === member.id ? 'var(--cream)' : undefined }}><td><div className="table-primary">{member.name}</div><div className="table-secondary">{member.email}</div></td><td>{ROLE_LABELS[member.role]}</td><td>{member.permissions.length} de 6</td><td><span className={`status-badge ${member.active ? 'status-badge--success' : 'status-badge--danger'}`}><span className="status-dot" />{member.active ? 'Ativo' : 'Suspenso'}</span></td><td>{member.lastAccess}</td><td><MoreHorizontal size={17} /></td></tr>)}</tbody></table></div></section><section className="settings-card" style={{ marginTop: 18 }}><h2>{selected.name}</h2><p>{selected.email} · {ROLE_LABELS[selected.role]}</p><div className="filter-pills">{['Reservas', 'Agenda', 'Clientes', 'Cardápio', 'Relatórios', 'Configurações'].map((permission, index) => <span className={`filter-pill ${selected.permissions.length > index ? 'active' : ''}`} key={permission}>{selected.permissions.length > index ? '✓ ' : ''}{permission}</span>)}</div></section></AdminPage>;
}

export function ReportsView() {
  return <AdminPage active="/admin/relatorios" title="Relatórios" subtitle="Dados que contam boas histórias."><div className="admin-toolbar"><div className="filter-pills"><button className="filter-pill">Últimos 7 dias</button><button className="filter-pill active">Últimos 30 dias</button><button className="filter-pill">Este mês</button></div><label className="field-shell"><CalendarDays size={16} /><input type="date" defaultValue="2026-09-01" /><span>→</span><input type="date" defaultValue="2026-09-21" /></label></div><div className="admin-grid"><StatCard icon={<CalendarDays size={19} />} label="Reservas do período" value="312" detail="↑ 18% vs. período anterior" /><StatCard icon={<Users size={19} />} label="Pessoas atendidas" value="1.248" detail="↑ 22% vs. período anterior" tone="olive" /><StatCard icon={<X size={19} />} label="Cancelamentos" value="28" detail="↑ 7%" tone="gold" /><StatCard icon={<CircleAlert size={19} />} label="No-show" value="16" detail="↓ 20%" tone="olive" /></div><div className="admin-two-col"><section className="admin-panel"><header className="admin-panel__header"><h2>Reservas por dia</h2><span className="muted">Por dia</span></header><div className="admin-panel__body"><div className="bar-chart" style={{ height: 260 }}>{[24, 40, 35, 52, 47, 65, 58, 70, 45, 61, 74, 68, 52, 60, 78, 56, 64, 82, 72, 48].map((height, index) => <span key={index} style={{ height: `${height}%` }} />)}</div><div className="bar-chart__labels"><span>01/09</span><span>05/09</span><span>10/09</span><span>15/09</span><span>20/09</span></div></div></section><section className="admin-panel"><header className="admin-panel__header"><h2>Horários mais fortes</h2></header><div className="admin-panel__body"><div className="data-list">{['19:00', '20:00', '13:00', '14:00', '21:00'].map((time, index) => <div className="data-row" key={time} style={{ gridTemplateColumns: '32px 1fr auto' }}><strong>{index + 1}</strong><div className="data-row__name">{time}</div><span>{68 - index * 7} reservas</span></div>)}</div></div></section></div></AdminPage>;
}

export function ContentView() {
  return <AdminPage active="/admin/conteudo" title="Conteúdo do site" subtitle="Gerencie as informações que aparecem no site público."><div className="admin-form-card"><section className="form-card"><h2>Hero da página inicial</h2><div className="form-stack"><img src={content.heroImageUrl} alt="Prévia do hero" style={{ width: '100%', height: 190, objectFit: 'cover' }} /><label className="form-label"><span>Título principal</span><textarea defaultValue={content.heroTitle} /></label><label className="form-label"><span>Subtítulo</span><textarea defaultValue={content.heroSubtitle} /></label><Button><Save size={16} /> Salvar alterações</Button></div></section><aside className="side-summary"><h2>Pré-visualização</h2><div className="settings-card" style={{ padding: 0, overflow: 'hidden' }}><img src={content.heroImageUrl} alt="Prévia do site" style={{ width: '100%', height: 250, objectFit: 'cover' }} /><div style={{ padding: 18 }}><p className="eyebrow">{settings.city}</p><h2 style={{ margin: '10px 0', fontSize: 28 }}>{content.heroTitle}</h2><p>{content.heroSubtitle}</p><LinkButton href="/" variant="secondary">Abrir site <ExternalLink size={15} /></LinkButton></div></div></aside></div><div className="settings-grid" style={{ marginTop: 18 }}>{[{ title: 'Chef', text: content.chefName, icon: Utensils }, { title: 'Fotos da galeria', text: `${content.gallery.length} fotos`, icon: ImageIcon }, { title: 'Textos e redes', text: 'Sobre, destaques e experiência', icon: MessageCircle }].map(({ title, text, icon: Icon }) => <article className="settings-card" key={title}><Icon color="var(--terracotta)" /><h2>{title}</h2><p>{text}</p><button className="panel-link">Editar <ChevronRight size={14} style={{ verticalAlign: 'middle' }} /></button></article>)}</div></AdminPage>;
}

export function SettingsView() {
  return <AdminPage active="/admin/configuracoes" title="Configurações" subtitle="Gerencie as informações do seu restaurante."><div className="settings-grid">{[{ title: 'Horários', text: 'Segunda a sábado · 12:00 às 23:00', icon: Clock3 }, { title: 'WhatsApp', text: `+${settings.whatsapp}`, icon: MessageCircle }, { title: 'Endereço', text: settings.address, icon: MapPin }, { title: 'Capacidade', text: `${tables.reduce((sum, table) => sum + table.capacity, 0)} lugares cadastrados`, icon: Users }, { title: 'Áreas e mesas', text: `${areas.length} áreas · ${tables.length} mesas`, icon: Table2 }, { title: 'Textos do site', text: 'Hero, chef, galeria e redes sociais', icon: Settings2 }].map(({ title, text, icon: Icon }) => <article className="settings-card" key={title}><Icon color="var(--terracotta)" size={22} /><h2>{title}</h2><p>{text}</p><Button variant="ghost"><Edit3 size={15} /> Editar</Button></article>)}</div><section className="admin-panel" style={{ marginTop: 18 }}><header className="admin-panel__header"><h2>Horários de funcionamento</h2><Button variant="ghost"><Save size={15} /> Salvar horários</Button></header><div className="admin-panel__body"><div className="data-list">{['Segunda-feira', 'Terça-feira', 'Quarta-feira', 'Quinta-feira', 'Sexta-feira', 'Sábado', 'Domingo'].map((day, index) => <div className="data-row" key={day} style={{ gridTemplateColumns: '1fr 130px 130px' }}><strong>{day}</strong><input className="field-shell" type="time" defaultValue={index === 6 ? '' : '12:00'} disabled={index === 6} /><input className="field-shell" type="time" defaultValue={index === 6 ? '' : index > 3 ? '23:00' : '22:00'} disabled={index === 6} /></div>)}</div></div></section></AdminPage>;
}

export function SetupView() {
  return <AdminPage active="/admin/configuracoes" title="Modo demonstração" subtitle="Conecte o backend quando quiser. Enquanto isso, explore uma demonstração com dados de exemplo."><div className="admin-form-card"><section className="form-card"><img src={photoUrls.room} alt="Ambiente Baru" style={{ width: '100%', height: 260, objectFit: 'cover' }} /><p className="eyebrow" style={{ marginTop: 22 }}>Sistema pronto</p><h2>Firebase não configurado</h2><p className="muted">O sistema está funcionando em modo de demonstração, com dados de exemplo. Para utilizar dados reais, configure o projeto Firebase do Baru.</p><div className="timeline">{['Configurar projeto Firebase', 'Adicionar variáveis de ambiente', 'Ativar Firestore', 'Configurar autenticação', 'Publicar dados reais'].map((step, index) => <div className="timeline-item" key={step}><strong>{index + 1}. {step}</strong><span>Disponível no guia de configuração.</span></div>)}</div><div className="form-actions"><Button><ExternalLink size={16} /> Usar dados de demonstração</Button><LinkButton href="/admin/configuracoes" variant="ghost">Ver configurações</LinkButton></div></section><aside className="side-summary"><h2>Status do sistema</h2>{[['Sistema operacional', 'Modo demo'], ['Banco de dados', 'Não conectado'], ['Última verificação', 'Agora'], ['Compatível com Firebase', 'Sim']].map(([label, value]) => <div className="summary-line" key={label}><span>{label}</span><strong style={{ marginLeft: 'auto', color: value === 'Sim' || value === 'Modo demo' ? 'var(--success)' : 'var(--warning)', fontSize: 12 }}>{value}</strong></div>)}</aside></div></AdminPage>;
}
