'use client';

import { Banknote, CheckCircle2, LockKeyhole, Minus, Plus, ReceiptText, WalletCards } from 'lucide-react';
import { collection, doc, getDocs, setDoc, updateDoc } from 'firebase/firestore';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { AdminPage } from '@/components/admin-shell';
import { Button, LoadingState } from '@/components/baru-ui';
import { firebaseAuth, firebaseDb, isFirebaseDataMode } from '@/lib/firebase-client';
import { formatMoney } from '@/shared/baru-domain';

type CashRegister = { id: string; status: 'OPEN' | 'CLOSED'; operatorUid: string; operatorEmail?: string; openedAt: string; closedAt?: string; openingDate: string; initialBalanceCents: number; expectedCashCents?: number; countedCashCents?: number; differenceCents?: number; closingNote?: string; updatedAt?: string };
type CashMovement = { id: string; registerId: string; type: 'SALE' | 'WITHDRAWAL' | 'SUPPLY' | 'REFUND'; direction: 'IN' | 'OUT'; amountCents: number; cashAmountCents: number; operatorUid: string; paymentMethod?: 'PIX' | 'CARD' | 'CASH' | 'OTHER'; note?: string; createdAt: string };

function id(prefix: string): string { return `${prefix}-${crypto.randomUUID()}`; }
function today(): string { return new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo' }).format(new Date()); }

export function CashManagerView() {
  const [registers, setRegisters] = useState<CashRegister[]>([]);
  const [movements, setMovements] = useState<CashMovement[]>([]);
  const [opening, setOpening] = useState('');
  const [movement, setMovement] = useState({ type: 'SUPPLY' as CashMovement['type'], amount: '', note: '' });
  const [counted, setCounted] = useState('');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const current = registers.find((register) => register.status === 'OPEN') || null;
  const currentMovements = movements.filter((item) => item.registerId === current?.id);
  const expectedCash = useMemo(() => (current?.initialBalanceCents || 0) + currentMovements.reduce((sum, item) => sum + (item.direction === 'IN' ? item.cashAmountCents : -item.cashAmountCents), 0), [current, currentMovements]);
  const load = async () => { if (!isFirebaseDataMode() || !firebaseDb) { setLoading(false); return; } try { const [registerSnapshot, movementSnapshot] = await Promise.all([getDocs(collection(firebaseDb, 'cashRegisters')), getDocs(collection(firebaseDb, 'cashMovements'))]); setRegisters(registerSnapshot.docs.map((item) => ({ id: item.id, ...item.data() }) as CashRegister)); setMovements(movementSnapshot.docs.map((item) => ({ id: item.id, ...item.data() }) as CashMovement)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível carregar o caixa real.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const requireOperator = () => { if (!firebaseDb || !firebaseAuth?.currentUser) throw new Error('A sessão Firebase da equipe não está disponível.'); return { db: firebaseDb, user: firebaseAuth.currentUser }; };
  const open = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); try { const { db, user } = requireOperator(); const cents = Math.round(Number(opening.replace(',', '.')) * 100); if (!Number.isSafeInteger(cents) || cents < 0) throw new Error('Informe um saldo inicial válido.'); const register: CashRegister = { id: id('cash'), status: 'OPEN', operatorUid: user.uid, ...(user.email ? { operatorEmail: user.email } : {}), openedAt: new Date().toISOString(), openingDate: today(), initialBalanceCents: cents, updatedAt: new Date().toISOString() }; await setDoc(doc(db, 'cashRegisters', register.id), register); setRegisters((currentRegisters) => [register, ...currentRegisters]); setOpening(''); setMessage('Caixa aberto no Firebase.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível abrir o caixa.'); } finally { setSaving(false); } };
  const addMovement = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!current) return; setSaving(true); setError(''); try { const { db, user } = requireOperator(); const cents = Math.round(Number(movement.amount.replace(',', '.')) * 100); if (!Number.isSafeInteger(cents) || cents <= 0) throw new Error('Informe um valor maior que zero.'); const isOut = movement.type === 'WITHDRAWAL' || movement.type === 'REFUND'; const next: CashMovement = { id: id('movement'), registerId: current.id, type: movement.type, direction: isOut ? 'OUT' : 'IN', amountCents: cents, cashAmountCents: cents, operatorUid: user.uid, paymentMethod: 'CASH', note: movement.note.trim().slice(0, 240), createdAt: new Date().toISOString() }; await setDoc(doc(db, 'cashMovements', next.id), next); setMovements((currentMovementsValue) => [next, ...currentMovementsValue]); setMovement({ type: 'SUPPLY', amount: '', note: '' }); setMessage('Movimentação registrada no Firebase.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível registrar a movimentação.'); } finally { setSaving(false); } };
  const close = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!current) return; setSaving(true); setError(''); try { const { db } = requireOperator(); const cents = Math.round(Number(counted.replace(',', '.')) * 100); if (!Number.isSafeInteger(cents) || cents < 0) throw new Error('Informe o valor contado em dinheiro.'); const next = { ...current, status: 'CLOSED' as const, closedAt: new Date().toISOString(), countedCashCents: cents, expectedCashCents: expectedCash, differenceCents: cents - expectedCash, updatedAt: new Date().toISOString() }; await updateDoc(doc(db, 'cashRegisters', current.id), next); setRegisters((currentRegisters) => currentRegisters.map((register) => register.id === current.id ? next : register)); setCounted(''); setMessage('Caixa fechado e conferência salva no Firebase.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível fechar o caixa.'); } finally { setSaving(false); } };
  if (loading) return <AdminPage active="/admin/caixa" title="Caixa" subtitle="Carregando registros reais."><LoadingState /></AdminPage>;
  return <AdminPage active="/admin/caixa" title="Caixa" subtitle="Abertura, conferência e movimentações persistidas." actions={<Button variant="ghost" onClick={load}>Atualizar</Button>}>
    {!isFirebaseDataMode() && <p className="field-error" role="alert">O modo demo não grava caixa. Ative o Firebase real.</p>}{error && <p className="field-error" role="alert">{error}</p>}{message && <p className="field-error" style={{ color: 'var(--success)' }} role="status">{message}</p>}
    {!current ? <form className="form-card" onSubmit={open}><div style={{ display: 'flex', gap: 12, alignItems: 'center' }}><Banknote color="var(--terracotta)" /><div><p className="eyebrow">Novo turno</p><h2>Abrir caixa</h2></div></div><p className="muted">Informe o dinheiro inicial disponível para troco.</p><label className="form-label"><span>Saldo inicial (R$) *</span><input value={opening} onChange={(event) => setOpening(event.target.value)} inputMode="decimal" placeholder="100,00" required /></label><Button type="submit" disabled={saving || !isFirebaseDataMode()}><Plus size={16} /> Abrir caixa</Button></form> : <>
      <div className="admin-grid"><article className="settings-card"><Banknote color="var(--terracotta)" /><p>Saldo inicial</p><strong>{formatMoney(current.initialBalanceCents)}</strong></article><article className="settings-card"><WalletCards color="var(--terracotta)" /><p>Dinheiro esperado</p><strong>{formatMoney(expectedCash)}</strong></article><article className="settings-card"><CheckCircle2 color="var(--success)" /><p>Status</p><strong>Caixa aberto</strong></article></div>
      <form className="form-card" style={{ marginTop: 18 }} onSubmit={addMovement}><h2>Registrar movimentação</h2><div className="form-row"><label className="form-label"><span>Tipo</span><select value={movement.type} onChange={(event) => setMovement({ ...movement, type: event.target.value as CashMovement['type'] })}><option value="SUPPLY">Suprimento</option><option value="WITHDRAWAL">Sangria</option><option value="SALE">Venda em dinheiro</option><option value="REFUND">Estorno</option></select></label><label className="form-label"><span>Valor (R$) *</span><input value={movement.amount} onChange={(event) => setMovement({ ...movement, amount: event.target.value })} inputMode="decimal" required /></label></div><label className="form-label"><span>Motivo</span><input value={movement.note} onChange={(event) => setMovement({ ...movement, note: event.target.value })} maxLength={240} required /></label><Button type="submit" disabled={saving}><ReceiptText size={16} /> Registrar</Button></form>
      <form className="form-card" style={{ marginTop: 18 }} onSubmit={close}><h2>Fechar caixa</h2><p className="muted">Conte o dinheiro físico e registre a diferença contra o esperado.</p><label className="form-label"><span>Valor contado (R$) *</span><input value={counted} onChange={(event) => setCounted(event.target.value)} inputMode="decimal" required /></label><div className="form-actions"><Button type="submit" disabled={saving}><LockKeyhole size={16} /> Fechar e salvar conferência</Button></div></form>
      <section className="admin-panel" style={{ marginTop: 18 }}><header className="admin-panel__header"><h2>Movimentações do turno</h2><span className="muted">{currentMovements.length} registros</span></header><div className="admin-panel__body"><div className="data-list">{currentMovements.map((item) => <div className="data-row" key={item.id}><div><strong>{item.type === 'SUPPLY' ? 'Suprimento' : item.type === 'WITHDRAWAL' ? 'Sangria' : item.type === 'REFUND' ? 'Estorno' : 'Venda'}</strong><div className="table-secondary">{item.note || 'Sem observação'}</div></div><strong>{item.direction === 'OUT' ? '-' : '+'}{formatMoney(item.amountCents)}</strong></div>)}{!currentMovements.length && <p className="muted">Nenhuma movimentação neste turno.</p>}</div></div></section>
    </>}
    {!current && registers.length > 0 && <section className="admin-panel" style={{ marginTop: 18 }}><header className="admin-panel__header"><h2>Histórico de caixas</h2><Minus size={16} /></header><div className="admin-panel__body"><div className="data-list">{registers.filter((register) => register.status === 'CLOSED').slice(0, 10).map((register) => <div className="data-row" key={register.id}><span>{register.openingDate}</span><div><strong>{formatMoney(register.initialBalanceCents)} inicial</strong><div className="table-secondary">Contado: {formatMoney(register.countedCashCents || 0)}</div></div><strong>{formatMoney(register.differenceCents || 0)}</strong></div>)}</div></div></section>}
  </AdminPage>;
}
