'use client';

import { ArrowLeft, Plus, Save, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { AdminPage } from '@/components/admin-shell';
import { Button, LinkButton, LoadingState } from '@/components/baru-ui';
import { readOrderSettingsAsync, saveOrderSettingsAsync } from '@/lib/order-repository';
import { isFirebaseDataMode } from '@/lib/firebase-client';
import type { DeliveryZone, FulfillmentMode, OrderOperationsSettings, PaymentMethod } from '@/shared/order-domain';

const modeLabels: Record<FulfillmentMode, string> = { PICKUP: 'Retirada no Baru', DELIVERY: 'Entrega', DINE_IN: 'Consumo no local' };
const paymentLabels: Record<PaymentMethod, string> = { PIX: 'Pix', CARD_ON_DELIVERY: 'Cartão na entrega/retirada', CASH: 'Dinheiro' };
const newZone = (): DeliveryZone => ({ id: `zone-${crypto.randomUUID().slice(0, 8)}`, name: '', feeCents: 0, active: true });

export function OrderSettingsManagerView() {
  const [draft, setDraft] = useState<OrderOperationsSettings | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { readOrderSettingsAsync().then(setDraft).catch(() => setError('Não foi possível carregar a configuração de pedidos.')).finally(() => setLoading(false)); }, []);
  const toggleMode = (mode: FulfillmentMode) => { if (!draft) return; const next = draft.fulfillmentModes.includes(mode) ? draft.fulfillmentModes.filter((value) => value !== mode) : [...draft.fulfillmentModes, mode]; setDraft({ ...draft, fulfillmentModes: next }); };
  const togglePayment = (method: PaymentMethod) => { if (!draft) return; const next = draft.paymentMethods.includes(method) ? draft.paymentMethods.filter((value) => value !== method) : [...draft.paymentMethods, method]; setDraft({ ...draft, paymentMethods: next }); };
  const updateZone = (index: number, patch: Partial<DeliveryZone>) => { if (!draft) return; setDraft({ ...draft, deliveryZones: draft.deliveryZones.map((zone, zoneIndex) => zoneIndex === index ? { ...zone, ...patch } : zone) }); };
  const save = async () => { if (!draft) return; setSaving(true); setMessage(''); setError(''); try { const normalized = { ...draft, deliveryZones: draft.deliveryZones.map((zone) => ({ ...zone, name: zone.name.trim() })) }; await saveOrderSettingsAsync(normalized); setDraft(normalized); setMessage('Configuração de pedidos salva no Firebase.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível salvar a configuração.'); } finally { setSaving(false); } };
  if (loading || !draft) return <AdminPage active="/admin/configuracoes" title="Pedidos internos" subtitle="Carregando configuração real."><LoadingState /></AdminPage>;
  return <AdminPage active="/admin/configuracoes" title="Pedidos internos" subtitle="Modos, pagamentos, pausa e zonas usados pelo checkout." actions={<LinkButton href="/admin/configuracoes" variant="ghost"><ArrowLeft size={16} /> Configurações gerais</LinkButton>}>
    {!isFirebaseDataMode() && <p className="field-error" role="alert">Ative o Firebase real para publicar a operação.</p>}{error && <p className="field-error" role="alert">{error}</p>}{message && <p className="field-error" style={{ color: 'var(--success)' }} role="status">{message}</p>}
    <section className="form-card"><div className="form-stack"><label className="muted"><input type="checkbox" checked={draft.acceptingOrders} onChange={(event) => setDraft({ ...draft, acceptingOrders: event.target.checked })} /> Aceitar pedidos agora</label><label className="form-label"><span>Mensagem quando pausado</span><input value={draft.pauseMessage} onChange={(event) => setDraft({ ...draft, pauseMessage: event.target.value })} maxLength={240} /></label><div className="filter-pills"><span className="muted">Recebimento:</span>{(Object.keys(modeLabels) as FulfillmentMode[]).map((mode) => <label className={draft.fulfillmentModes.includes(mode) ? 'filter-pill active' : 'filter-pill'} key={mode}><input type="checkbox" checked={draft.fulfillmentModes.includes(mode)} onChange={() => toggleMode(mode)} /> {modeLabels[mode]}</label>)}</div><div className="filter-pills"><span className="muted">Pagamento:</span>{(Object.keys(paymentLabels) as PaymentMethod[]).map((method) => <label className={draft.paymentMethods.includes(method) ? 'filter-pill active' : 'filter-pill'} key={method}><input type="checkbox" checked={draft.paymentMethods.includes(method)} onChange={() => togglePayment(method)} /> {paymentLabels[method]}</label>)}</div><div className="form-row"><label className="form-label"><span>Taxa padrão (centavos)</span><input type="number" min="0" value={draft.deliveryFeeCents} onChange={(event) => setDraft({ ...draft, deliveryFeeCents: Number(event.target.value) })} /></label><label className="form-label"><span>Pedido mínimo (centavos)</span><input type="number" min="0" value={draft.minimumOrderCents} onChange={(event) => setDraft({ ...draft, minimumOrderCents: Number(event.target.value) })} /></label><label className="form-label"><span>Estimativa (minutos)</span><input type="number" min="5" max="240" value={draft.orderEstimateMinutes} onChange={(event) => setDraft({ ...draft, orderEstimateMinutes: Number(event.target.value) })} /></label></div></div></section>
    <section className="admin-panel" style={{ marginTop: 18 }}><header className="admin-panel__header"><div><h2>Zonas de entrega</h2><p className="muted">Quando houver zonas ativas, o checkout exigirá uma delas e usará sua taxa.</p></div><Button variant="ghost" onClick={() => setDraft({ ...draft, deliveryZones: [...draft.deliveryZones, newZone()] })}><Plus size={16} /> Nova zona</Button></header><div className="admin-panel__body"><div className="data-list">{draft.deliveryZones.map((zone, index) => <div className="data-row" key={zone.id} style={{ gridTemplateColumns: '1fr 180px auto', gap: 12 }}><input className="field-shell" value={zone.name} onChange={(event) => updateZone(index, { name: event.target.value })} placeholder="Centro" maxLength={120} /><input className="field-shell" type="number" min="0" value={zone.feeCents} onChange={(event) => updateZone(index, { feeCents: Number(event.target.value) })} aria-label={`Taxa de ${zone.name || 'zona'}`} /><div className="form-actions"><label className="muted"><input type="checkbox" checked={zone.active} onChange={(event) => updateZone(index, { active: event.target.checked })} /> Ativa</label><button type="button" className="icon-button" aria-label={`Remover ${zone.name || 'zona'}`} onClick={() => setDraft({ ...draft, deliveryZones: draft.deliveryZones.filter((_, zoneIndex) => zoneIndex !== index) })}><Trash2 size={15} /></button></div></div>)}{!draft.deliveryZones.length && <div className="empty-state"><p>Nenhuma zona publicada. A taxa padrão será usada quando a entrega estiver habilitada.</p></div>}</div></div></section>
    <div className="form-actions" style={{ marginTop: 18 }}><Button onClick={save} disabled={saving || !isFirebaseDataMode()}><Save size={16} /> {saving ? 'Salvando…' : 'Salvar operação de pedidos'}</Button></div>
  </AdminPage>;
}
