'use client';

import { BookOpen, CalendarDays, Check, ChevronRight, CircleAlert, Clock3, Edit3, ExternalLink, Image as ImageIcon, MapPin, MessageCircle, MoreHorizontal, Plus, Save, Search, Settings2, Table2, UserPlus, Users, Utensils, X } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { AdminPage } from '@/components/admin-shell';
import { Button, LinkButton, StatCard, StatusBadge } from '@/components/baru-ui';
import { areas, categories, content, customers, menuItems, photoUrls, reservations as seedReservations, settings, tables, team } from '@/lib/baru-data';
import { buildWhatsappLink, createReservationAsync, readAreasAsync, readCategoriesAsync, readContentAsync, readCustomersAsync, readMenuItemsAsync, readReservations, readReservationsAsync, readSettingsAsync, readTablesAsync, readTeamAsync, updateReservationAsync } from '@/lib/baru-repository';
import { appCheckEnabled, firebaseConfigured, firebaseProjectId, firebaseSdkConfigAvailable, isFirebaseDataMode, productionEnvironmentReady } from '@/lib/firebase-client';
import { formatDate, formatMoney, generateTimeSlots, normalizeWhatsapp, RESERVATION_STATUS_LABELS, ROLE_LABELS, validateReservation, type Reservation, type ReservationStatus, type RestaurantSettings, type RestaurantTable, type SiteContent, type TeamMember } from '@/shared/baru-domain';

function useRepositoryCollection<T>(demoItems: T[], loader: () => Promise<T[]>) {
  const [items, setItems] = useState<T[]>(() => isFirebaseDataMode() ? [] : demoItems.map((item) => ({ ...item })));
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { let active = true; setLoading(true); loader().then((next) => { if (active) setItems(next); }).catch(() => { if (active) setError('Não foi possível carregar os dados reais deste módulo.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [loader]);
  return { items, loading, error };
}

function useRepositorySettings() {
  const [value, setValue] = useState<RestaurantSettings | null>(() => isFirebaseDataMode() ? null : settings);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { let active = true; readSettingsAsync().then((next) => { if (active) setValue(next); }).catch(() => { if (active) setError('Não foi possível carregar as configurações reais.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  return { value, loading, error };
}

export function ReservationManager() {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState<'ALL' | ReservationStatus>('ALL');
  const [items, setItems] = useState(() => readReservations());
  const [error, setError] = useState('');
  useEffect(() => { let active = true; readReservationsAsync().then((next) => { if (active) setItems(next); }).catch(() => { if (active) setError('Não foi possível sincronizar as reservas.'); }); return () => { active = false; }; }, []);
  const filtered = items.filter((item) => (status === 'ALL' || item.status === status) && `${item.customerName} ${item.code} ${item.whatsapp}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminPage active="/admin/reservas" title="Reservas" subtitle="Gerencie as reservas do restaurante." actions={<LinkButton href="/admin/reservas/nova"><Plus size={17} /> Nova reserva</LinkButton>}>{error && <p className="field-error" role="status">{error}</p>}<div className="admin-toolbar"><div className="filter-pills">{(['ALL', 'NEW', 'CONFIRMED', 'ARRIVED', 'COMPLETED', 'CANCELLED'] as const).map((value) => <button key={value} className={`filter-pill ${status === value ? 'active' : ''}`} onClick={() => setStatus(value)}>{value === 'ALL' ? 'Todas' : value === 'NEW' ? 'Pendentes' : RESERVATION_STATUS_LABELS[value]}</button>)}</div><label className="field-shell" style={{ minWidth: 260 }}><Search size={16} /><span className="visually-hidden">Buscar reserva</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar nome, telefone ou código…" /></label></div><section className="admin-panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Código</th><th>Cliente</th><th>Data e horário</th><th>Pessoas</th><th>Mesa</th><th>Status</th><th aria-label="Ações" /></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td className="table-primary">#{item.code.replace('BRU-', '')}</td><td><div className="table-primary">{item.customerName}</div><div className="table-secondary">{item.whatsapp}</div></td><td>{formatDate(item.date)}<div className="table-secondary">{item.time}</div></td><td>{item.partySize}</td><td>{item.tableId?.replace('mesa-', 'Mesa ') || '—'}</td><td><StatusBadge status={item.status} /></td><td><a className="icon-button" href={`/admin/reservas/${item.id}/editar`} aria-label={`Editar ${item.code}`}><Edit3 size={15} /></a></td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state"><CircleAlert size={20} /><h2>Nenhuma reserva encontrada</h2><p>Altere os filtros ou cadastre uma nova reserva.</p></div>}</div></section></AdminPage>;
}

function ReservationFields({ form, setForm, includeStatus = false, settingsValue = settings, tablesValue = tables }: { form: { name: string; whatsapp: string; date: string; time: string; partySize: string; tableId: string; note: string; status: ReservationStatus }; setForm: (next: (current: typeof form) => typeof form) => void; includeStatus?: boolean; settingsValue?: RestaurantSettings; tablesValue?: RestaurantTable[] }) {
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <div className="form-stack"><label className="form-label"><span>Cliente *</span><input value={form.name} onChange={(event) => set('name', event.target.value)} placeholder="Nome completo" required /></label><label className="form-label"><span>WhatsApp *</span><input value={form.whatsapp} onChange={(event) => set('whatsapp', event.target.value)} placeholder="(45) 9 9988-7766" required /></label><div className="form-row"><label className="form-label"><span>Data *</span><input type="date" value={form.date} onChange={(event) => set('date', event.target.value)} required /></label><label className="form-label"><span>Horário *</span><select value={form.time} onChange={(event) => set('time', event.target.value)} required><option value="">Selecione</option>{generateTimeSlots(settingsValue, form.date).map((time) => <option key={time}>{time}</option>)}</select></label></div><div className="form-row"><label className="form-label"><span>Pessoas *</span><select value={form.partySize} onChange={(event) => set('partySize', event.target.value)}>{Array.from({ length: settingsValue.maxPartySize }, (_, index) => <option key={index + 1}>{index + 1}</option>)}</select></label><label className="form-label"><span>Área / Mesa *</span><select value={form.tableId} onChange={(event) => set('tableId', event.target.value)}><option value="">Mesa a definir</option>{tablesValue.filter((table) => table.active && table.state !== 'MAINTENANCE' && table.capacity >= Number(form.partySize)).map((table) => <option key={table.id} value={table.id}>{table.name} · {table.capacity} lugares</option>)}</select></label></div><label className="form-label"><span>Observação</span><textarea value={form.note} onChange={(event) => set('note', event.target.value)} maxLength={500} /></label>{includeStatus && <label className="form-label"><span>Status inicial</span><select value={form.status} onChange={(event) => set('status', event.target.value as ReservationStatus)}>{(Object.keys(RESERVATION_STATUS_LABELS) as ReservationStatus[]).map((value) => <option key={value} value={value}>{RESERVATION_STATUS_LABELS[value]}</option>)}</select></label>}</div>;
}

export function NewReservationForm() {
  const { value: liveSettings, loading: settingsLoading } = useRepositorySettings();
  const { items: liveTables, loading: tablesLoading } = useRepositoryCollection(tables, readTablesAsync);
  const [form, setForm] = useState(() => ({ name: '', whatsapp: '', date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10), time: '', partySize: '2', tableId: '', note: '', status: 'CONFIRMED' as ReservationStatus }));
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (submitting || !liveSettings) return; const validationErrors = validateReservation({ date: form.date, time: form.time, partySize: Number(form.partySize), customerName: form.name, whatsapp: form.whatsapp, note: form.note }, liveSettings); if (validationErrors.length) { setError(validationErrors[0]); return; } setSubmitting(true); try { const reservation = await createReservationAsync({ customerId: `customer-${form.name.toLowerCase().replace(/\W+/g, '-')}`, customerName: form.name.trim(), whatsapp: normalizeWhatsapp(form.whatsapp), date: form.date, time: form.time, partySize: Number(form.partySize), ...(form.tableId ? { tableId: form.tableId } : {}), note: form.note.trim(), status: form.status, source: 'ADMIN', idempotencyKey: `admin-${crypto.randomUUID()}` }); window.location.href = `/admin/reservas/${reservation.id}/editar`; } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível criar a reserva.'); setSubmitting(false); } };
  if (settingsLoading || tablesLoading || !liveSettings) return <AdminPage active="/admin/reservas" title="Nova reserva" subtitle="Carregando configurações reais."><div className="loading-state">Carregando…</div></AdminPage>;
  return <AdminPage active="/admin/reservas" title="Nova reserva" subtitle="Cadastre rapidamente uma nova reserva."><div className="admin-form-card"><form className="form-card" onSubmit={submit}><h2>Dados da reserva</h2><ReservationFields form={form} setForm={setForm} includeStatus settingsValue={liveSettings} tablesValue={liveTables} />{error && <p className="field-error" role="alert">{error}</p>}<div className="form-actions"><LinkButton href="/admin/reservas" variant="ghost">Cancelar</LinkButton><Button type="submit" disabled={submitting}><Save size={16} /> {submitting ? 'Criando…' : 'Criar reserva'} <ChevronRight size={16} /></Button></div></form><aside className="side-summary"><h2>Resumo da reserva</h2><img src={photoUrls.table} alt="Mesa preparada no Baru" /><div className="summary-line"><CalendarDays size={16} /> {form.date ? formatDate(form.date) : 'Escolha a data'}</div><div className="summary-line"><Clock3 size={16} /> {form.time || 'Escolha o horário'}</div><div className="summary-line"><Users size={16} /> {form.partySize} pessoas</div><div className="summary-line"><Table2 size={16} /> {form.tableId ? form.tableId.replace('mesa-', 'Mesa ') : 'Mesa a definir'}</div></aside></div></AdminPage>;
}

export function EditReservationForm({ id }: { id: string }) {
  const [original, setOriginal] = useState<Reservation | null>(null);
  const [form, setForm] = useState({ name: '', whatsapp: '', date: '', time: '', partySize: '2', tableId: '', note: '', status: 'NEW' as ReservationStatus });
  const [loading, setLoading] = useState(true);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState('');
  const { value: liveSettings } = useRepositorySettings();
  const { items: liveTables, loading: tablesLoading } = useRepositoryCollection(tables, readTablesAsync);
  useEffect(() => { let active = true; setLoading(true); readReservationsAsync().then((next) => { if (!active) return; const found = next.find((item) => item.id === id); setOriginal(found || null); if (found) setForm({ name: found.customerName, whatsapp: found.whatsapp, date: found.date, time: found.time, partySize: String(found.partySize), tableId: found.tableId || '', note: found.note, status: found.status }); else setError('Reserva não encontrada.'); setLoading(false); }).catch(() => { if (active) { setError('Não foi possível carregar a reserva atualizada.'); setLoading(false); } }); return () => { active = false; }; }, [id]);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!original || !liveSettings) return; setSaved(false); setError(''); const validationErrors = validateReservation({ date: form.date, time: form.time, partySize: Number(form.partySize), customerName: form.name, whatsapp: form.whatsapp, note: form.note }, liveSettings); if (validationErrors.length) { setError(validationErrors[0]); return; } try { await updateReservationAsync(id, { customerName: form.name.trim(), whatsapp: normalizeWhatsapp(form.whatsapp), date: form.date, time: form.time, partySize: Number(form.partySize), tableId: form.tableId || undefined, note: form.note.trim(), status: form.status }); setSaved(true); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível salvar. A reserva pode ter sido alterada por outra sessão.'); } };
  if (loading || tablesLoading || !liveSettings) return <AdminPage active="/admin/reservas" title="Editar reserva" subtitle="Carregando a reserva selecionada."><div className="loading-state">Carregando…</div></AdminPage>;
  if (!original) return <AdminPage active="/admin/reservas" title="Reserva não encontrada" subtitle="O código informado não corresponde a uma reserva disponível."><div className="empty-state"><CircleAlert size={20} /><h2>Não foi possível abrir esta reserva</h2><p>Verifique o endereço ou volte para a lista de reservas.</p><LinkButton href="/admin/reservas" variant="secondary">Voltar para reservas</LinkButton></div></AdminPage>;
  return <AdminPage active="/admin/reservas" title={error ? 'Editar reserva · atenção' : 'Editar reserva'} subtitle="Altere as informações da reserva abaixo."><div className="admin-form-card"><form className="form-card" onSubmit={save}><div className="code-panel" style={{ marginTop: 0 }}><div><small>Código da reserva</small><strong>{original.code}</strong></div><StatusBadge status={form.status} /></div><h2>Informações da reserva</h2><ReservationFields form={form} setForm={setForm} includeStatus settingsValue={liveSettings} tablesValue={liveTables} />{error && <p className="field-error" role="alert">{error}</p>}<div className="form-actions"><Button type="submit"><Save size={16} /> Salvar alterações</Button><LinkButton href={buildWhatsappLink(form.whatsapp, `Olá, ${form.name}! Falamos sobre a reserva ${original.code}.`)} variant="ghost"><MessageCircle size={16} /> WhatsApp</LinkButton></div>{saved && <p className="field-error" style={{ color: 'var(--success)' }} role="status">Alterações salvas.</p>}</form><aside className="side-summary"><h2>Histórico da reserva</h2><div className="timeline">{original.history.map((entry) => <div className="timeline-item" key={entry.id}><strong>{entry.label}</strong>{formatDate(entry.createdAt.slice(0, 10))} · por {entry.by}</div>)}</div><div className="settings-card" style={{ marginTop: 28 }}><strong>Dados de operação</strong><p>Origem: {original.source}<br />Última atualização: {formatDate(original.updatedAt.slice(0, 10))}</p></div></aside></div></AdminPage>;
}

export function AgendaView() {
  const { items: reservations, error: reservationsError } = useRepositoryCollection(seedReservations, readReservationsAsync);
  const { items: liveAreas } = useRepositoryCollection(areas, readAreasAsync);
  const { items: liveTables } = useRepositoryCollection(tables, readTablesAsync);
  const { value: liveSettings } = useRepositorySettings();
  const today = new Date().toISOString().slice(0, 10);
  const slots = liveSettings ? generateTimeSlots(liveSettings, today).filter((_, index) => index % 2 === 0) : [];
  const pending = reservations.filter((item) => item.date === today && item.status === 'NEW');
  const todayReservations = reservations.filter((item) => item.date === today && !['CANCELLED', 'NO_SHOW'].includes(item.status));
  const occupiedPeople = todayReservations.reduce((sum, item) => sum + item.partySize, 0);
  const peak = todayReservations.reduce<Record<string, number>>((counts, item) => ({ ...counts, [item.time]: (counts[item.time] || 0) + item.partySize }), {});
  const busiest = Object.entries(peak).sort(([, left], [, right]) => right - left)[0];
  return <AdminPage active="/admin/agenda" title="Agenda" subtitle="Organize hoje grandes experiências." actions={<LinkButton href="/admin/reservas/nova"><Plus size={17} /> Nova reserva</LinkButton>}>{reservationsError && <p className="field-error" role="alert">{reservationsError}</p>}<div className="admin-grid"><StatCard icon={<Users size={19} />} label="Pessoas no dia" value={String(occupiedPeople)} detail="Reservas não canceladas" tone="olive" /><StatCard icon={<CalendarDays size={19} />} label="Total de reservas" value={String(todayReservations.length)} detail="Dados do repository ativo" /><StatCard icon={<Clock3 size={19} />} label="Horário mais movimentado" value={busiest?.[0] || '—'} detail={busiest ? `${busiest[1]} pessoas` : 'Nenhuma reserva'} tone="gold" /><StatCard icon={<CircleAlert size={19} />} label="Pendentes" value={String(pending.length)} detail="Aguardando confirmação" /></div><section className="admin-panel"><header className="admin-panel__header"><h2>{new Intl.DateTimeFormat('pt-BR', { weekday: 'long', day: '2-digit', month: 'long' }).format(new Date())}</h2><span className="muted">Horários derivados das configurações</span></header><div className="admin-panel__body"><div className="table-wrap"><table className="data-table"><thead><tr><th>Horário</th>{liveAreas.map((area) => <th key={area.id}>{area.name}</th>)}</tr></thead><tbody>{slots.map((time) => <tr key={time}><td className="table-primary">{time}</td>{liveAreas.map((area) => { const reservation = todayReservations.find((item) => item.time === time && (liveTables.find((table) => table.id === item.tableId)?.areaId === area.id || (!item.tableId && area.id === liveAreas[0]?.id))); return <td key={area.id}>{reservation ? <a className="settings-card" style={{ display: 'block', padding: 10, background: reservation.status === 'NEW' ? '#faedcf' : '#e5efdf' }} href={`/admin/reservas/${reservation.id}/editar`}><strong style={{ fontSize: 12 }}>{reservation.customerName}</strong><span className="table-secondary">{reservation.partySize} pessoas · {reservation.status === 'NEW' ? 'Aguardando' : 'Confirmada'}</span></a> : <span className="muted">—</span>}</td>})}</tr>)}{!slots.length && <tr><td colSpan={Math.max(1, liveAreas.length + 1)}><div className="empty-state"><Clock3 size={20} /><h2>Horários não configurados</h2><p>Cadastre o horário de funcionamento no Firebase para montar a agenda.</p></div></td></tr>}</tbody></table></div></div></section></AdminPage>;
}

export function CustomersView() {
  const [query, setQuery] = useState('');
  const { items: liveCustomers, error } = useRepositoryCollection(customers, readCustomersAsync);
  const filtered = liveCustomers.filter((customer) => `${customer.name} ${customer.whatsapp} ${customer.notes}`.toLowerCase().includes(query.toLowerCase()));
  return <AdminPage active="/admin/clientes" title="Clientes" subtitle="Acompanhe histórico de reservas, contatos, no-show e observações."><div className="admin-toolbar"><label className="field-shell" style={{ flex: 1, maxWidth: 600 }}><Search size={16} /><span className="visually-hidden">Buscar clientes</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome, telefone ou observação…" /></label><span className="muted">{liveCustomers.length} clientes carregados do repository</span></div>{error && <p className="field-error" role="alert">{error}</p>}<section className="admin-panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Cliente</th><th>Última reserva</th><th>Total</th><th>No-show</th><th>Contato</th><th>Observações</th></tr></thead><tbody>{filtered.map((customer) => <tr key={customer.id}><td><a className="table-primary" href={`/admin/clientes/${customer.id}`}>{customer.name}</a><div className="table-secondary">{customer.tags.join(' · ')}</div></td><td>{customer.lastVisit ? formatDate(customer.lastVisit) : '—'}</td><td>{customer.reservationIds.length}</td><td>{customer.noShows}</td><td><a className="panel-link" href={buildWhatsappLink(customer.whatsapp, `Olá, ${customer.name}!`)} aria-label={`Falar com ${customer.name} no WhatsApp`}><MessageCircle size={16} /></a></td><td className="table-secondary">{customer.notes}</td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state"><Users size={20} /><h2>Nenhum cliente encontrado</h2><p>Os clientes reais aparecem aqui quando cadastrados no Firebase.</p></div>}</div></section></AdminPage>;
}

export function CustomerDetailView({ id }: { id: string }) {
  const { items: liveCustomers, loading: customersLoading, error: customersError } = useRepositoryCollection(customers, readCustomersAsync);
  const { items: reservations, loading: reservationsLoading } = useRepositoryCollection(seedReservations, readReservationsAsync);
  const customer = liveCustomers.find((item) => item.id === id);
  if (customersLoading || reservationsLoading) return <AdminPage active="/admin/clientes" title="Cliente" subtitle="Carregando dados reais."><div className="loading-state">Carregando…</div></AdminPage>;
  if (!customer) return <AdminPage active="/admin/clientes" title="Cliente não encontrado" subtitle="O cadastro solicitado não está disponível no repository atual."><div className="empty-state"><Users size={20} /><h2>Cliente não encontrado</h2><p>Volte para a lista e selecione um cadastro válido.</p><LinkButton href="/admin/clientes" variant="secondary">Voltar para clientes</LinkButton></div></AdminPage>;
  const customerReservations = reservations.filter((item) => item.customerId === customer.id || item.customerName === customer.name);
  return <AdminPage active="/admin/clientes" title={customer.name} subtitle="Histórico do cadastro no repository atual." actions={<><LinkButton href="/admin/reservas/nova"><Plus size={16} /> Nova reserva</LinkButton><LinkButton href={buildWhatsappLink(customer.whatsapp, `Olá, ${customer.name}!`)} variant="ghost"><MessageCircle size={16} /> WhatsApp</LinkButton></>}><>{customersError && <p className="field-error" role="alert">{customersError}</p>}<div className="filter-pills" style={{ marginBottom: 18 }}>{customer.tags.map((tag) => <span className="filter-pill active" key={tag}>{tag}</span>)}{customer.preferences.map((tag) => <span className="filter-pill" key={tag}>{tag}</span>)}</div><div className="admin-grid"><StatCard icon={<CalendarDays size={19} />} label="Total de reservas" value={String(customerReservations.length)} detail="Calculado pelo repository" /><StatCard icon={<Users size={19} />} label="Comparecimentos" value={String(Math.max(0, customerReservations.length - customer.noShows))} detail="Sem dados de presença" tone="olive" /><StatCard icon={<CircleAlert size={19} />} label="No-show" value={String(customer.noShows)} detail="Acompanhar" tone="gold" /><StatCard icon={<Utensils size={19} />} label="Ticket médio" value="—" detail="Valor não registrado" /></div><div className="admin-two-col"><section className="admin-panel"><header className="admin-panel__header"><h2>Últimas reservas</h2><a className="panel-link" href="/admin/reservas">Ver todas <ArrowRightIcon /></a></header><div className="admin-panel__body"><div className="data-list">{customerReservations.length ? customerReservations.map((reservation) => <div className="data-row" key={reservation.id}><strong>{formatDate(reservation.date)}</strong><div><div className="data-row__name">{reservation.time}</div><div className="data-row__meta">{reservation.partySize} pessoas · {reservation.tableId || 'Mesa não definida'}</div></div><StatusBadge status={reservation.status} /><a href={`/admin/reservas/${reservation.id}/editar`} aria-label={`Editar reserva ${reservation.code}`}><ChevronRight size={16} /></a></div>) : <p className="muted">Nenhuma reserva encontrada.</p>}</div></div></section><section className="admin-panel"><header className="admin-panel__header"><h2>Observações da equipe</h2><span className="muted">Somente leitura</span></header><div className="admin-panel__body"><p>{customer.notes || 'Nenhuma observação cadastrada.'}</p><hr style={{ border: 0, borderTop: '1px solid var(--line)', margin: '24px 0' }} /><h2 style={{ fontSize: 22 }}>Preferências</h2>{customer.preferences.map((preference) => <div className="summary-line" key={preference}><Check size={16} /> {preference}</div>)}</div></section></div></></AdminPage>;
}

function ArrowRightIcon() { return <ChevronRight size={14} style={{ verticalAlign: 'middle' }} />; }

export function MenuManagerView() {
  const [selected, setSelected] = useState('principais');
  const { items: liveCategories, error: categoriesError } = useRepositoryCollection(categories, readCategoriesAsync);
  const { items: liveItems, error: itemsError } = useRepositoryCollection(menuItems, readMenuItemsAsync);
  const activeCategory = liveCategories.find((category) => category.id === selected)?.id || liveCategories[0]?.id || '';
  const items = liveItems.filter((item) => item.categoryId === activeCategory);
  return <AdminPage active="/admin/cardapio" title="Gerenciar cardápio" subtitle="Itens e categorias do repository atual." actions={<Button disabled title="A edição do cardápio ainda precisa de um formulário persistente no Firebase."><Plus size={17} /> Novo item indisponível</Button>}>{(categoriesError || itemsError) && <p className="field-error" role="alert">{categoriesError || itemsError}</p>}<div className="card-grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', marginBottom: 22 }}>{liveCategories.map((category) => <button className={`settings-card ${activeCategory === category.id ? 'active' : ''}`} style={{ textAlign: 'left', borderColor: activeCategory === category.id ? 'var(--terracotta)' : 'var(--line)' }} key={category.id} onClick={() => setSelected(category.id)}><img src={liveItems.find((item) => item.categoryId === category.id)?.imageUrl || photoUrls.table} alt="" style={{ width: '100%', height: 90, objectFit: 'cover', marginBottom: 11 }} /><strong style={{ fontFamily: 'Georgia, serif', fontSize: 19 }}>{category.name}</strong><p style={{ margin: '5px 0 0' }}>{liveItems.filter((item) => item.categoryId === category.id).length} itens</p></button>)}{!liveCategories.length && <div className="empty-state"><Utensils size={20} /><h2>Cardápio real ainda não cadastrado</h2><p>Cadastre categorias e itens no Firebase para administrar o cardápio.</p></div>}</div><section className="admin-panel"><div className="table-wrap"><table className="data-table"><thead><tr><th>Item</th><th>Categoria</th><th>Preço</th><th>Status</th><th>Destaque</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><div style={{ display: 'flex', alignItems: 'center', gap: 12 }}><img src={item.imageUrl || photoUrls.table} alt="" style={{ width: 54, height: 42, objectFit: 'cover' }} /><div><div className="table-primary">{item.name}</div><div className="table-secondary">{item.description}</div></div></div></td><td>{liveCategories.find((category) => category.id === item.categoryId)?.name}</td><td>{formatMoney(item.priceCents)}</td><td><StatusBadge status={item.active ? 'CONFIRMED' : 'CANCELLED'} /></td><td>{item.featured ? '★' : '☆'}</td><td><button className="icon-button" disabled aria-label={`Editar ${item.name} — indisponível`}><Edit3 size={15} /></button></td></tr>)}</tbody></table>{!items.length && liveCategories.length > 0 && <div className="empty-state"><Utensils size={20} /><h2>Nenhum item nesta categoria</h2><p>O cadastro de itens precisa ser feito no backend até o formulário de edição ser liberado.</p></div>}</div></section></AdminPage>;
}

export function TablesView() {
  const { items: liveAreas, error: areasError } = useRepositoryCollection(areas, readAreasAsync);
  const { items: liveTables, error: tablesError } = useRepositoryCollection(tables, readTablesAsync);
  return <AdminPage active="/admin/mesas" title="Mesas e áreas" subtitle="Dados de áreas e mesas do repository atual." actions={<><Button variant="ghost" disabled title="O formulário de áreas ainda não está conectado ao Firebase."><Plus size={16} /> Nova área indisponível</Button><Button disabled title="O formulário de mesas ainda não está conectado ao Firebase."><Plus size={16} /> Nova mesa indisponível</Button></>}>{(areasError || tablesError) && <p className="field-error" role="alert">{areasError || tablesError}</p>}<div className="card-grid">{liveAreas.map((area) => { const areaTables = liveTables.filter((table) => table.areaId === area.id); return <article className="settings-card" key={area.id}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10 }}><div><p className="eyebrow">{area.active ? 'Área ativa' : 'Área inativa'}</p><h2>{area.name}</h2><p>{areaTables.length} mesas · {areaTables.reduce((sum, table) => sum + table.capacity, 0)} lugares</p></div><span className="muted">Somente leitura</span></div><div className="data-list">{areaTables.slice(0, 5).map((table) => <div className="data-row" key={`${area.id}-${table.id}`} style={{ gridTemplateColumns: '1fr auto' }}><div><strong>{table.name}</strong><div className="table-secondary">{table.capacity} lugares</div></div><StatusBadge status={table.state === 'AVAILABLE' ? 'CONFIRMED' : table.state === 'MAINTENANCE' ? 'CANCELLED' : 'NEW'} /></div>)}{!areaTables.length && <p className="muted">Nenhuma mesa cadastrada nesta área.</p>}</div></article>; })}{!liveAreas.length && <div className="empty-state"><Table2 size={20} /><h2>Áreas reais ainda não cadastradas</h2><p>Cadastre áreas e mesas no Firebase antes de operar este módulo.</p></div>}</div></AdminPage>;
}

export function TeamView() {
  const [members, setMembers] = useState<TeamMember[]>(() => isFirebaseDataMode() ? [] : team);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [query, setQuery] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { let active = true; readTeamAsync().then((next) => { if (active) setMembers(next); }).catch(() => { if (active) setError('Não foi possível carregar a equipe no Firebase.'); }); return () => { active = false; }; }, []);
  const filtered = members.filter((member) => `${member.name} ${member.email} ${member.role}`.toLowerCase().includes(query.toLowerCase()));
  const selected = members.find((member) => member.id === selectedId) || filtered[0] || null;
  const permissionLabels: Array<[string, string]> = [['Reservas', 'RESERVATIONS'], ['Agenda', 'AGENDA'], ['Clientes', 'CUSTOMERS'], ['Cardápio', 'MENU'], ['Relatórios', 'REPORTS'], ['Configurações', 'SETTINGS']];
  return <AdminPage active="/admin/equipe" title="Equipe" subtitle="Usuários e permissões lidos do Firebase." actions={<Button disabled><UserPlus size={17} /> Convites em breve</Button>}>{error && <p className="field-error" role="alert">{error}</p>}<section className="admin-panel"><div className="admin-toolbar" style={{ padding: '18px 22px', margin: 0, borderBottom: '1px solid var(--line)' }}><label className="field-shell" style={{ flex: 1, maxWidth: 560 }}><Search size={16} /><span className="visually-hidden">Buscar equipe</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por nome, e-mail ou função…" /></label></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Nome</th><th>Função</th><th>Permissões</th><th>Status</th><th>Último acesso</th><th /></tr></thead><tbody>{filtered.map((member) => <tr key={member.id} onClick={() => setSelectedId(member.id)} style={{ cursor: 'pointer', background: selected?.id === member.id ? 'var(--cream)' : undefined }}><td><div className="table-primary">{member.name}</div><div className="table-secondary">{member.email}</div></td><td>{ROLE_LABELS[member.role]}</td><td>{member.permissions.length} de 6</td><td><span className={`status-badge ${member.active ? 'status-badge--success' : 'status-badge--danger'}`}><span className="status-dot" />{member.active ? 'Ativo' : 'Suspenso'}</span></td><td>{member.lastAccess || '—'}</td><td><MoreHorizontal size={17} /></td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state"><Users size={20} /><h2>Nenhum membro cadastrado</h2><p>Cadastre usuários no Firebase para que apareçam nesta área.</p></div>}</div></section>{selected && <section className="settings-card" style={{ marginTop: 18 }}><h2>{selected.name}</h2><p>{selected.email} · {ROLE_LABELS[selected.role]}</p><div className="filter-pills">{permissionLabels.map(([label, permission]) => <span className={`filter-pill ${selected.permissions.includes(permission) ? 'active' : ''}`} key={permission}>{selected.permissions.includes(permission) ? '✓ ' : ''}{label}</span>)}</div></section>}</AdminPage>;
}

export function ReportsView() {
  const [items, setItems] = useState(() => readReservations());
  const [error, setError] = useState('');
  useEffect(() => { let active = true; readReservationsAsync().then((next) => { if (active) setItems(next); }).catch(() => { if (active) setError('Não foi possível atualizar os relatórios.'); }); return () => { active = false; }; }, []);
  const today = new Date();
  const start = new Date(today.getFullYear(), today.getMonth(), today.getDate() - 30).toISOString().slice(0, 10);
  const period = items.filter((item) => item.date >= start && item.date <= today.toISOString().slice(0, 10));
  const activeReservations = period.filter((item) => !['CANCELLED', 'NO_SHOW'].includes(item.status));
  const canceled = period.filter((item) => item.status === 'CANCELLED').length;
  const noShows = period.filter((item) => item.status === 'NO_SHOW').length;
  const hourLabels = Array.from(new Set(period.map((item) => item.time))).sort();
  const hourCounts = hourLabels.map((hour) => period.filter((item) => item.time === hour).length);
  const maxHourCount = Math.max(1, ...hourCounts);
  return <AdminPage active="/admin/relatorios" title="Relatórios" subtitle="Dados que contam boas histórias.">{error && <p className="field-error" role="status">{error}</p>}<div className="admin-toolbar"><span className="muted">Últimos 30 dias · {start} → {today.toISOString().slice(0, 10)}</span></div><div className="admin-grid"><StatCard icon={<CalendarDays size={19} />} label="Reservas do período" value={String(period.length)} detail="Calculado pelo repository" /><StatCard icon={<Users size={19} />} label="Pessoas atendidas" value={String(activeReservations.reduce((sum, item) => sum + item.partySize, 0))} detail="Reservas não canceladas" tone="olive" /><StatCard icon={<X size={19} />} label="Cancelamentos" value={String(canceled)} detail="No período" tone="gold" /><StatCard icon={<CircleAlert size={19} />} label="No-show" value={String(noShows)} detail="Acompanhar com a equipe" tone="olive" /></div><div className="admin-two-col"><section className="admin-panel"><header className="admin-panel__header"><h2>Reservas por horário</h2><span className="muted">Horários presentes nos dados</span></header><div className="admin-panel__body">{hourLabels.length ? <><div className="bar-chart" style={{ height: 260 }}>{hourCounts.map((count, index) => <span key={hourLabels[index]} style={{ height: `${Math.max(8, count / maxHourCount * 100)}%` }} />)}</div><div className="bar-chart__labels">{hourLabels.map((hour) => <span key={hour}>{hour}</span>)}</div></> : <p className="muted">Ainda não há reservas no período para montar o gráfico.</p>}</div></section><section className="admin-panel"><header className="admin-panel__header"><h2>Horários mais fortes</h2></header><div className="admin-panel__body"><div className="data-list">{hourLabels.slice().sort((left, right) => (period.filter((item) => item.time === right).length - period.filter((item) => item.time === left).length)).map((time, index) => <div className="data-row" key={time} style={{ gridTemplateColumns: '32px 1fr auto' }}><strong>{index + 1}</strong><div className="data-row__name">{time}</div><span>{period.filter((item) => item.time === time).length} reservas</span></div>)}{!hourLabels.length && <p className="muted">Sem dados de horário.</p>}</div></div></section></div></AdminPage>;
}

export function ContentView() {
  const { value: liveSettings, loading: settingsLoading } = useRepositorySettings();
  const [siteContent, setSiteContent] = useState<SiteContent | null>(() => isFirebaseDataMode() ? null : content);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  useEffect(() => { let active = true; readContentAsync().then((next) => { if (active) setSiteContent(next); }).catch(() => { if (active) setError('Não foi possível carregar o conteúdo real do site.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  if (loading || settingsLoading) return <AdminPage active="/admin/conteudo" title="Conteúdo do site" subtitle="Carregando dados reais."><div className="loading-state">Carregando…</div></AdminPage>;
  if (!siteContent || !liveSettings) return <AdminPage active="/admin/conteudo" title="Conteúdo do site" subtitle="O conteúdo ainda não foi cadastrado no Firebase."><div className="empty-state"><BookOpenIcon /><h2>Conteúdo real não cadastrado</h2><p>O painel não exibe o conteúdo de demonstração no modo Firebase.</p></div></AdminPage>;
  return <AdminPage active="/admin/conteudo" title="Conteúdo do site" subtitle="Visualização do conteúdo publicado. A edição ficará disponível quando o formulário persistente estiver conectado.">{error && <p className="field-error" role="alert">{error}</p>}<div className="admin-form-card"><section className="form-card"><h2>Hero da página inicial</h2><div className="form-stack"><img src={siteContent.heroImageUrl} alt="Prévia do hero" style={{ width: '100%', height: 190, objectFit: 'cover' }} /><label className="form-label"><span>Título principal</span><textarea defaultValue={siteContent.heroTitle} disabled /></label><label className="form-label"><span>Subtítulo</span><textarea defaultValue={siteContent.heroSubtitle} disabled /></label><Button disabled title="A persistência do conteúdo ainda não foi conectada."><Save size={16} /> Salvar indisponível</Button></div></section><aside className="side-summary"><h2>Pré-visualização</h2><div className="settings-card" style={{ padding: 0, overflow: 'hidden' }}><img src={siteContent.heroImageUrl} alt="Prévia do site" style={{ width: '100%', height: 250, objectFit: 'cover' }} /><div style={{ padding: 18 }}><p className="eyebrow">{liveSettings.city}</p><h2 style={{ margin: '10px 0', fontSize: 28 }}>{siteContent.heroTitle}</h2><p>{siteContent.heroSubtitle}</p><LinkButton href="/" variant="secondary">Abrir site <ExternalLink size={15} /></LinkButton></div></div></aside></div><div className="settings-grid" style={{ marginTop: 18 }}>{[{ title: 'Chef', text: siteContent.chefName, icon: Utensils }, { title: 'Fotos da galeria', text: `${siteContent.gallery.length} fotos`, icon: ImageIcon }, { title: 'Textos e redes', text: 'Somente leitura até a persistência ser conectada', icon: MessageCircle }].map(({ title, text, icon: Icon }) => <article className="settings-card" key={title}><Icon color="var(--terracotta)" /><h2>{title}</h2><p>{text}</p></article>)}</div></AdminPage>;
}

function BookOpenIcon() { return <BookOpen size={20} />; }

export function SettingsView() {
  const { value: liveSettings, loading: settingsLoading, error: settingsError } = useRepositorySettings();
  const { items: liveAreas } = useRepositoryCollection(areas, readAreasAsync);
  const { items: liveTables } = useRepositoryCollection(tables, readTablesAsync);
  if (settingsLoading || !liveSettings) return <AdminPage active="/admin/configuracoes" title="Configurações" subtitle="Carregando dados reais."><div className="loading-state">Carregando…</div></AdminPage>;
  const days: Array<[string, keyof RestaurantSettings['openingHours']]> = [['Segunda-feira', 'monday'], ['Terça-feira', 'tuesday'], ['Quarta-feira', 'wednesday'], ['Quinta-feira', 'thursday'], ['Sexta-feira', 'friday'], ['Sábado', 'saturday'], ['Domingo', 'sunday']];
  const openingSummary = days.filter(([, key]) => !liveSettings.openingHours[key].closed).map(([day, key]) => `${day.replace('-feira', '')} · ${liveSettings.openingHours[key].open}–${liveSettings.openingHours[key].close}`).join(' · ');
  return <AdminPage active="/admin/configuracoes" title="Configurações" subtitle="Visualize as informações operacionais do repository atual.">{settingsError && <p className="field-error" role="alert">{settingsError}</p>}<div className="settings-grid">{[{ title: 'Horários', text: openingSummary || 'Não configurado', icon: Clock3 }, { title: 'WhatsApp', text: `+${liveSettings.whatsapp}`, icon: MessageCircle }, { title: 'Endereço', text: liveSettings.address, icon: MapPin }, { title: 'Capacidade', text: `${liveTables.reduce((sum, table) => sum + table.capacity, 0)} lugares cadastrados`, icon: Users }, { title: 'Áreas e mesas', text: `${liveAreas.length} áreas · ${liveTables.length} mesas`, icon: Table2 }, { title: 'Textos do site', text: 'Gerenciados no módulo Conteúdo', icon: Settings2 }].map(({ title, text, icon: Icon }) => <article className="settings-card" key={title}><Icon color="var(--terracotta)" size={22} /><h2>{title}</h2><p>{text}</p><span className="muted">Somente leitura</span></article>)}</div><section className="admin-panel" style={{ marginTop: 18 }}><header className="admin-panel__header"><h2>Horários de funcionamento</h2><Button variant="ghost" disabled title="A persistência das configurações ainda não está conectada."><Save size={15} /> Salvar indisponível</Button></header><div className="admin-panel__body"><div className="data-list">{days.map(([day, key]) => <div className="data-row" key={day} style={{ gridTemplateColumns: '1fr 130px 130px' }}><strong>{day}</strong><input className="field-shell" type="time" value={liveSettings.openingHours[key].open} disabled readOnly /><input className="field-shell" type="time" value={liveSettings.openingHours[key].close} disabled readOnly /></div>)}</div></div></section></AdminPage>;
}

export function SetupView() {
  const connected = isFirebaseDataMode();
  return <AdminPage active="/admin/configuracoes" title="Status do ambiente" subtitle="Status verificável do Firebase e do modo de dados."><div className="admin-form-card"><section className="form-card"><img src={photoUrls.room} alt="Ambiente Baru" style={{ width: '100%', height: 260, objectFit: 'cover' }} /><p className="eyebrow" style={{ marginTop: 22 }}>{connected ? 'Backend selecionado' : 'Modo controlado'}</p><h2>{connected ? 'Firebase Baru selecionado' : 'Demonstração local ativa'}</h2><p className="muted">{connected ? `O SDK modular aponta para o projeto ${firebaseProjectId}. Os dados operacionais não usam seeds quando o modo Firebase está ativo.` : 'A interface está funcionando com dados fictícios e persistência local. Ative o modo Firebase somente com ambiente de produção validado.'}</p><div className="timeline">{[['Configuração Web explícita', firebaseSdkConfigAvailable ? 'Disponível' : 'Ausente'], ['Firestore Rules', 'Publicadas'], ['Repository de reservas', 'Disponível'], ['Authentication por e-mail', 'Disponível'], ['App Check', appCheckEnabled ? 'Ativo' : 'Pendente']].map(([step, value], index) => <div className="timeline-item" key={step}><strong>{index + 1}. {step}</strong><span>{value}</span></div>)}</div><div className="form-actions"><LinkButton href="/admin/configuracoes" variant="ghost">Ver configurações</LinkButton></div></section><aside className="side-summary"><h2>Status do sistema</h2>{[['Sistema operacional', connected ? 'Firebase' : 'Modo demo'], ['Projeto', firebaseProjectId || 'Não configurado'], ['SDK Web', firebaseConfigured ? 'Inicializável' : 'Ausente'], ['Ambiente produção', productionEnvironmentReady ? 'Pronto' : 'Não validado'], ['App Check', appCheckEnabled ? 'Ativo' : 'Pendente']].map(([label, value]) => <div className="summary-line" key={label}><span>{label}</span><strong style={{ marginLeft: 'auto', color: value === 'Inicializável' || value === 'Firebase' || value === 'Modo demo' || value === 'Pronto' || value === 'Ativo' ? 'var(--success)' : 'var(--warning)', fontSize: 12 }}>{value}</strong></div>)}</aside></div></AdminPage>;
}
