'use client';

import { Check, Plus, Save, SlidersHorizontal } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { AdminPage } from '@/components/admin-shell';
import { Button, LoadingState } from '@/components/baru-ui';
import { readModifierGroupsAsync, readModifiersAsync, saveModifierAsync, saveModifierGroupAsync } from '@/lib/catalog-repository';
import { isFirebaseDataMode } from '@/lib/firebase-client';
import { formatMoney } from '@/shared/baru-domain';
import type { OrderModifier, OrderModifierGroup } from '@/shared/order-domain';

const newModifier = (): Partial<OrderModifier> & Pick<OrderModifier, 'name'> => ({ name: '', priceCents: 0, active: true, available: true, displayOrder: 0 });
const newGroup = (): Partial<OrderModifierGroup> & Pick<OrderModifierGroup, 'name'> => ({ name: '', description: '', active: true, required: false, minSelections: 0, maxSelections: 1, allowDuplicate: false, modifierIds: [], displayOrder: 0 });

export function ModifierManagerView() {
  const [modifiers, setModifiers] = useState<OrderModifier[]>([]);
  const [groups, setGroups] = useState<OrderModifierGroup[]>([]);
  const [modifierDraft, setModifierDraft] = useState(newModifier());
  const [groupDraft, setGroupDraft] = useState(newGroup());
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const [nextModifiers, nextGroups] = await Promise.all([readModifiersAsync(), readModifierGroupsAsync()]); setModifiers(nextModifiers); setGroups(nextGroups); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível carregar os adicionais.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const saveModifier = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); try { const next = await saveModifierAsync(modifierDraft); setModifiers((current) => current.some((item) => item.id === next.id) ? current.map((item) => item.id === next.id ? next : item) : [next, ...current]); setModifierDraft(newModifier()); setMessage('Adicional salvo no Firebase.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível salvar o adicional.'); } finally { setSaving(false); } };
  const saveGroup = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); try { const next = await saveModifierGroupAsync(groupDraft); setGroups((current) => current.some((item) => item.id === next.id) ? current.map((item) => item.id === next.id ? next : item) : [next, ...current]); setGroupDraft(newGroup()); setMessage('Grupo de adicionais salvo no Firebase.'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível salvar o grupo.'); } finally { setSaving(false); } };
  if (loading) return <AdminPage active="/admin/adicionais" title="Adicionais" subtitle="Carregando registros reais."><LoadingState /></AdminPage>;
  return <AdminPage active="/admin/adicionais" title="Adicionais" subtitle="Monte grupos e opções que entram no cálculo do pedido." actions={<Button variant="ghost" onClick={() => { setModifierDraft(newModifier()); setGroupDraft(newGroup()); }}><Plus size={16} /> Novo cadastro</Button>}>
    {!isFirebaseDataMode() && <p className="field-error" role="alert">O modo demo não grava adicionais. Ative o Firebase real para editar.</p>}
    {error && <p className="field-error" role="alert">{error}</p>}{message && <p className="field-error" style={{ color: 'var(--success)' }} role="status">{message}</p>}
    <div className="admin-two-col"><section className="admin-panel"><header className="admin-panel__header"><h2>Opções cadastradas</h2><span className="muted">{modifiers.length} registros</span></header><div className="admin-panel__body"><div className="data-list">{modifiers.map((modifier) => <button className="data-row" style={{ textAlign: 'left', border: 0, width: '100%', background: 'transparent' }} key={modifier.id} onClick={() => setModifierDraft(modifier)}><div><strong>{modifier.name}</strong><div className="table-secondary">{formatMoney(modifier.priceCents)} · {modifier.available ? 'Disponível' : 'Indisponível'}</div></div><span className="muted">Editar</span></button>)}{!modifiers.length && <p className="muted">Nenhum adicional cadastrado.</p>}</div></div></section><form className="form-card" onSubmit={saveModifier}><p className="eyebrow">Opção individual</p><h2>{modifierDraft.id ? 'Editar adicional' : 'Novo adicional'}</h2><div className="form-stack"><label className="form-label"><span>Nome *</span><input value={modifierDraft.name} onChange={(event) => setModifierDraft({ ...modifierDraft, name: event.target.value })} required maxLength={100} /></label><label className="form-label"><span>Preço (centavos)</span><input type="number" min="0" max="1000000" value={modifierDraft.priceCents ?? 0} onChange={(event) => setModifierDraft({ ...modifierDraft, priceCents: Number(event.target.value) })} /></label><label className="form-label"><span>Quantidade máxima por item</span><input type="number" min="1" max="20" value={modifierDraft.maxQuantity ?? 1} onChange={(event) => setModifierDraft({ ...modifierDraft, maxQuantity: Number(event.target.value) })} /></label><label className="muted"><input type="checkbox" checked={modifierDraft.available !== false} onChange={(event) => setModifierDraft({ ...modifierDraft, available: event.target.checked })} /> Disponível para seleção</label><Button type="submit" disabled={saving || !isFirebaseDataMode()}><Save size={16} /> Salvar adicional</Button></div></form></div>
    <div className="admin-two-col" style={{ marginTop: 18 }}><section className="admin-panel"><header className="admin-panel__header"><h2>Grupos publicados</h2><SlidersHorizontal size={18} /></header><div className="admin-panel__body"><div className="data-list">{groups.map((group) => <button className="data-row" style={{ textAlign: 'left', border: 0, width: '100%', background: 'transparent' }} key={group.id} onClick={() => setGroupDraft(group)}><div><strong>{group.name}</strong><div className="table-secondary">{group.modifierIds.length} opções · {group.required ? 'Obrigatório' : 'Opcional'}</div></div><span className="muted">Editar</span></button>)}{!groups.length && <p className="muted">Nenhum grupo cadastrado.</p>}</div></div></section><form className="form-card" onSubmit={saveGroup}><p className="eyebrow">Configuração do produto</p><h2>{groupDraft.id ? 'Editar grupo' : 'Novo grupo'}</h2><div className="form-stack"><label className="form-label"><span>Nome *</span><input value={groupDraft.name} onChange={(event) => setGroupDraft({ ...groupDraft, name: event.target.value })} required maxLength={100} /></label><label className="form-label"><span>Descrição</span><input value={groupDraft.description || ''} onChange={(event) => setGroupDraft({ ...groupDraft, description: event.target.value })} maxLength={240} /></label><div className="form-row"><label className="form-label"><span>Mínimo</span><input type="number" min="0" max="30" value={groupDraft.minSelections ?? 0} onChange={(event) => setGroupDraft({ ...groupDraft, minSelections: Number(event.target.value) })} /></label><label className="form-label"><span>Máximo</span><input type="number" min="1" max="30" value={groupDraft.maxSelections ?? 1} onChange={(event) => setGroupDraft({ ...groupDraft, maxSelections: Number(event.target.value) })} /></label></div><label className="muted"><input type="checkbox" checked={Boolean(groupDraft.required)} onChange={(event) => setGroupDraft({ ...groupDraft, required: event.target.checked })} /> Exigir seleção</label><fieldset className="form-stack"><legend className="form-label">Opções do grupo</legend>{modifiers.map((modifier) => <label className="muted" key={modifier.id}><input type="checkbox" checked={Boolean(groupDraft.modifierIds?.includes(modifier.id))} onChange={(event) => setGroupDraft({ ...groupDraft, modifierIds: event.target.checked ? [...(groupDraft.modifierIds || []), modifier.id] : (groupDraft.modifierIds || []).filter((id) => id !== modifier.id) })} /> {eventLabel(modifier)}{groupDraft.modifierIds?.includes(modifier.id) && <Check size={14} />}</label>)}</fieldset><Button type="submit" disabled={saving || !isFirebaseDataMode()}><Save size={16} /> Salvar grupo</Button></div></form></div>
  </AdminPage>;
}

function eventLabel(modifier: OrderModifier): string { return `${modifier.name} · ${formatMoney(modifier.priceCents)}`; }
