'use client';

import { ArrowRight, Bike, Check, Clock3, PackageCheck, Store, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { AdminPage } from '@/components/admin-shell';
import { Button, LinkButton, LoadingState } from '@/components/baru-ui';
import { readOrdersAsync, updateOrderStatusAsync, watchOrders } from '@/lib/order-repository';
import { formatOrderMoney, ORDER_STATUS_LABELS, ORDER_TRANSITIONS, type OrderRecord, type OrderStatus } from '@/shared/order-domain';

const filters: Array<OrderStatus | 'ALL'> = ['ALL', 'NEW', 'CONFIRMED', 'PREPARING', 'READY', 'OUT_FOR_DELIVERY', 'COMPLETED', 'CANCELLED'];

function nextLabel(status: OrderStatus): string | null { const next = ORDER_TRANSITIONS[status]?.[0]; return next ? ({ CONFIRMED: 'Confirmar', PREPARING: 'Iniciar preparo', READY: 'Marcar pronto', OUT_FOR_DELIVERY: 'Saiu para entrega', COMPLETED: 'Concluir', CANCELLED: 'Cancelar' } as Record<string, string>)[next] || null : null; }

export function OrderManagerView() {
  const [orders, setOrders] = useState<OrderRecord[]>([]);
  const [filter, setFilter] = useState<OrderStatus | 'ALL'>('ALL');
  const [error, setError] = useState('');
  const [saving, setSaving] = useState('');
  useEffect(() => { let active = true; readOrdersAsync().then((next) => { if (active) setOrders(next); }).catch(() => setError('Não foi possível carregar os pedidos.')); const stop = watchOrders((next) => { if (active) setOrders(next); }); return () => { active = false; stop(); }; }, []);
  const visible = useMemo(() => orders.filter((order) => filter === 'ALL' || order.status === filter), [filter, orders]);
  const update = async (order: OrderRecord, status: OrderStatus) => { setSaving(order.id); setError(''); try { await updateOrderStatusAsync(order.id, status); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível atualizar o pedido.'); } finally { setSaving(''); } };
  return <AdminPage active="/admin/pedidos" title="Pedidos" subtitle="Operação interna em tempo real.">{error && <p className="field-error" role="alert">{error}</p>}<div className="filter-pills">{filters.map((value) => <button className={`filter-pill ${filter === value ? 'active' : ''}`} key={value} onClick={() => setFilter(value)}>{value === 'ALL' ? 'Todos' : ORDER_STATUS_LABELS[value]}</button>)}</div><section className="admin-panel" style={{ marginTop: 18 }}><div className="table-wrap"><table className="data-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Recebimento</th><th>Total</th><th>Status</th><th>Ação</th></tr></thead><tbody>{visible.map((order) => { const next = ORDER_TRANSITIONS[order.status]?.[0]; return <tr key={order.id}><td><div className="table-primary">{order.orderNumber}</div><div className="table-secondary">{order.publicCode}</div></td><td><div className="table-primary">{order.customer.name}</div><div className="table-secondary">{order.customer.whatsapp}</div></td><td>{order.fulfillment.mode === 'PICKUP' ? <><Store size={14} /> Retirada</> : order.fulfillment.mode === 'DELIVERY' ? <><Bike size={14} /> Entrega</> : <><PackageCheck size={14} /> Local</>}</td><td>{formatOrderMoney(order.pricing.totalCents)}</td><td><span className={`status-badge ${order.status === 'CANCELLED' ? 'status-badge--danger' : order.status === 'COMPLETED' ? 'status-badge--success' : 'status-badge--warning'}`}><span className="status-dot" />{ORDER_STATUS_LABELS[order.status]}</span></td><td><div className="form-actions"><LinkButton href={`/admin/pedidos/${order.id}`} variant="ghost" aria-label={`Abrir ${order.orderNumber}`}><ArrowRight size={15} /></LinkButton>{next && <Button onClick={() => update(order, next)} disabled={saving === order.id}>{saving === order.id ? '…' : nextLabel(order.status)}</Button>} {order.status !== 'CANCELLED' && order.status !== 'COMPLETED' && <Button variant="ghost" onClick={() => update(order, 'CANCELLED')} disabled={saving === order.id}><X size={15} /> Cancelar</Button>}</div></td></tr>; })}</tbody></table>{!visible.length && <div className="empty-state"><Clock3 size={20} /><h2>Nenhum pedido neste filtro</h2><p>Pedidos internos novos aparecerão aqui quando o cliente concluir o checkout.</p></div>}</div></section></AdminPage>;
}

export function OrderDetailView({ id }: { id: string }) {
  const [order, setOrder] = useState<OrderRecord | null>(null);
  const [error, setError] = useState('');
  useEffect(() => { let active = true; readOrdersAsync().then((next) => { if (active) setOrder(next.find((item) => item.id === id) || null); }).catch(() => { if (active) setError('Não foi possível carregar este pedido.'); }); return () => { active = false; }; }, [id]);
  if (!order && !error) return <AdminPage active="/admin/pedidos" title="Pedido" subtitle="Carregando dados reais."><LoadingState /></AdminPage>;
  if (!order) return <AdminPage active="/admin/pedidos" title="Pedido não encontrado"><div className="empty-state"><X size={20} /><h2>Pedido não encontrado</h2><LinkButton href="/admin/pedidos">Voltar</LinkButton></div></AdminPage>;
  const next = ORDER_TRANSITIONS[order.status]?.[0];
  return <AdminPage active="/admin/pedidos" title={`${order.orderNumber}`} subtitle="Detalhe operacional do pedido.">{error && <p className="field-error" role="alert">{error}</p>}<div className="admin-two-col"><section className="admin-panel"><header className="admin-panel__header"><h2>Itens e valores</h2><span className="muted">{ORDER_STATUS_LABELS[order.status]}</span></header><div className="admin-panel__body">{order.items.map((item) => <div className="data-row" key={item.cartItemId}><div><strong>{item.quantity}x {item.productName}</strong><div className="table-secondary">{item.sizeLabel} · {item.modifierSelections.flatMap((group) => group.items.map((modifier) => `${modifier.quantity}x ${modifier.name}`)).join(', ')}</div>{item.notes && <div className="table-secondary">Observação: {item.notes}</div>}</div><strong>{formatOrderMoney(item.totalPriceCents)}</strong></div>)}<div className="summary-line" style={{ marginTop: 20, fontSize: 20 }}><strong>Total</strong><strong>{formatOrderMoney(order.pricing.totalCents)}</strong></div></div></section><aside className="side-summary"><h2>Cliente</h2><p><strong>{order.customer.name}</strong><br />{order.customer.whatsapp}<br />{order.customer.email || 'Sem e-mail'}</p><h2 style={{ marginTop: 22 }}>Recebimento</h2><p>{order.fulfillment.mode === 'DELIVERY' ? 'Entrega' : order.fulfillment.mode === 'PICKUP' ? 'Retirada' : 'Consumo no local'}</p>{order.customer.address && <p>{order.customer.address.street}, {order.customer.address.number}<br />{order.customer.address.neighborhood}</p>}<h2 style={{ marginTop: 22 }}>Pagamento</h2><p>{order.payment.method === 'PIX' ? 'Pix' : order.payment.method === 'CASH' ? 'Dinheiro' : 'Cartão na entrega/retirada'}</p>{order.notes && <p><strong>Observação:</strong> {order.notes}</p>}<div className="form-actions" style={{ marginTop: 22 }}>{next && <Button onClick={async () => { try { await updateOrderStatusAsync(order.id, next); setOrder({ ...order, status: next, statusMessage: ORDER_STATUS_LABELS[next] }); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Não foi possível atualizar.'); } }}><Check size={15} /> {nextLabel(order.status)}</Button>}<LinkButton href="/admin/pedidos" variant="ghost">Voltar</LinkButton></div></aside></div><section className="settings-card" style={{ marginTop: 18 }}><h2>Histórico</h2><div className="timeline">{order.history?.map((entry, index) => <div className="timeline-item" key={`${entry.status}-${index}`}><strong>{ORDER_STATUS_LABELS[entry.status]}</strong><span>{entry.label}</span></div>)}</div></section></AdminPage>;
}
