'use client';

import { Search, ArrowRight } from 'lucide-react';
import { useMemo, useState } from 'react';
import { LinkButton } from '@/components/baru-ui';
import { PageHero, PublicLayout } from '@/components/public-shell';
import { categories, menuItems, moments, photoUrls } from '@/lib/baru-data';
import { formatMoney, type ServiceMomentId } from '@/shared/baru-domain';

export default function MenuPage() {
  const [selectedMoment, setSelectedMoment] = useState<ServiceMomentId | 'all'>('all');
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => menuItems.filter((item) => (selectedMoment === 'all' || item.serviceMomentIds.includes(selectedMoment)) && `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())), [query, selectedMoment]);
  return <PublicLayout><main className="menu-page"><PageHero className="menu-hero" eyebrow="Sabores da nossa terra" title="Cardápio" description="Ingredientes do mundo. Raízes da nossa terra. Uma cozinha que conta histórias." imageUrl={photoUrls.steak}><LinkButton href="/reservar">Reservar mesa <ArrowRight size={16} /></LinkButton></PageHero><section className="public-section"><nav className="menu-tabs" aria-label="Momentos do Baru"><button className={`menu-tab ${selectedMoment === 'all' ? 'active' : ''}`} onClick={() => setSelectedMoment('all')}>Todos</button>{moments.map((moment) => <button key={moment.id} className={`menu-tab ${selectedMoment === moment.id ? 'active' : ''}`} onClick={() => setSelectedMoment(moment.id)}>{moment.name}</button>)}</nav><div className="menu-toolbar"><label className="field-shell field-shell--search"><Search size={17} aria-hidden="true" /><span className="visually-hidden">Buscar no cardápio</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar um prato, ingrediente ou categoria…" /></label><label className="field-shell"><span className="visually-hidden">Filtrar categoria</span><select onChange={(event) => setSelectedMoment(event.target.value as ServiceMomentId | 'all')} value={selectedMoment}><option value="all">Todos os itens</option>{moments.map((moment) => <option key={moment.id} value={moment.id}>{moment.name}</option>)}</select></label></div>{categories.map((category) => { const items = filtered.filter((item) => item.categoryId === category.id); if (!items.length) return null; return <section className="menu-category" key={category.id}><div className="menu-category__heading"><div><h2>{category.name}</h2><p className="eyebrow">{category.subtitle}</p></div><p>{category.id === 'cafe' ? 'Cafés especiais, receitas afetivas e sabores para começar bem.' : 'Pratos autorais e ingredientes frescos para compartilhar a mesa.'}</p></div><div className="menu-grid">{items.map((item) => <article className="menu-item" key={item.id}><img src={item.imageUrl} alt={item.name} /><div className="menu-item__title"><h3>{item.name}</h3><strong>{formatMoney(item.priceCents)}</strong></div><p>{item.description}</p>{item.featured && <span className="mini-badge">Destaque</span>}</article>)}</div></section>})}{!filtered.length && <p className="empty-state">Nenhum item encontrado. Tente outro termo ou momento.</p>}</section><section className="cta-band" style={{ '--cta-image': `url(${photoUrls.restaurant})` } as React.CSSProperties}><div className="cta-band__inner"><div><p className="eyebrow">Momentos à mesa</p><h2>Boa comida aproxima pessoas.</h2></div><LinkButton href="/reservar">Reservar mesa <ArrowRight size={16} /></LinkButton></div></section></main></PublicLayout>;
}
